import { ATTACK_MODIFIER_CARD } from '../ATTACK_MODIFIER_CARD';
import { ELEMENT } from '../ELEMENT';
import { ENEMY } from '../ENEMY';
import { SLOT } from '../SLOT';
import { SUMMON } from '../SUMMON';
import ID from './ID';
import TYPE from './TYPE';
import AFTER from './AFTER_TYPE';
import EFFECT from './EFFECT_TYPE';
import WHAT from './WHAT_TYPE';
import WHEN from './WHEN_TYPE';

export default {
  // Items 1-14 (Prosperity 1)
  [ID.BOOTS_OF_STRIDING]: {
    id: ID.BOOTS_OF_STRIDING,
    name: 'Boots of Striding',
    desc: 'During your movement, add +2 (Symbol:Move) to a single movement.',
    count: 2,
    gold: 20,
    effects: '',
    when: { type: WHEN.MOVEMENT },
    what: [{ type: WHAT.ADD_X_MOVEMENT, count: 2 }],
    after: AFTER.SPENT,
    slot: SLOT.LEGS,
    type: TYPE.PROSPERITY,
    prosperity: 1,
  },
  [ID.WINGED_SHOES]: {
    id: ID.WINGED_SHOES,
    name: 'Winged Shoes',
    desc: 'During your movement, add (Symbol:Jump) to the movement.',
    count: 2,
    gold: 20,
    effects: '',
    when: { type: WHEN.MOVEMENT },
    what: [{ type: WHAT.JUMP, count: 2 }],
    after: AFTER.SPENT,
    slot: SLOT.LEGS,
    type: TYPE.PROSPERITY,
    prosperity: 1,
  },
  [ID.HIDE_ARMOR]: {
    id: ID.HIDE_ARMOR,
    name: 'Hide Armor',
    desc: 'On the next two sources of damage from attacks targeting you, gain (Symbol:Shield) 1.',
    count: 2,
    gold: 10,
    effects: '(Symbol:AttackNeg1) x2',
    when: { type: WHEN.NEXT_X_SOURCES_OF_DAMAGE, count: 2 },
    what: [{ type: WHAT.SHIELD, count: 1 }],
    after: AFTER.SPENT,
    slot: SLOT.BODY,
    type: TYPE.PROSPERITY,
    prosperity: 1,
  },
  [ID.LEATHER_ARMOR]: {
    id: ID.LEATHER_ARMOR,
    name: 'Leather Armor',
    desc: 'When attacked, the attacker gains Disadvantage on the attack.',
    count: 2,
    gold: 20,
    effects: '',
    when: { type: WHEN.ATTACKED },
    what: [{ type: WHAT.ATTACKER_DISADVANTAGE }],
    after: AFTER.SPENT,
    slot: SLOT.BODY,
    type: TYPE.PROSPERITY,
    prosperity: 1,
  },
  [ID.CLOAK_OF_INVISIBILITY]: {
    id: ID.CLOAK_OF_INVISIBILITY,
    name: 'Cloak of Invisibility',
    desc: 'During your turn, gain (Effect:Invisible).',
    count: 2,
    gold: 20,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.INVISIBLE }],
    after: AFTER.CONSUMED,
    slot: SLOT.BODY,
    type: TYPE.PROSPERITY,
    prosperity: 1,
  },
  [ID.EAGLE_EYE_GOGGLES]: {
    id: ID.EAGLE_EYE_GOGGLES,
    name: 'Eagle-Eye Goggles',
    desc: 'During your attack, gain Advantage on the entire Attack action.',
    count: 2,
    gold: 30,
    effects: '',
    when: { type: WHEN.ENTIRE_ATTACK_ACTION },
    what: [{ type: WHAT.ADVANTAGE }],
    after: AFTER.SPENT,
    slot: SLOT.HEAD,
    type: TYPE.PROSPERITY,
    prosperity: 1,
  },
  [ID.IRON_HELMET]: {
    id: ID.IRON_HELMET,
    name: 'Iron Helmet',
    desc: 'When attacked, consider any (Attack:2x) attack modifier card the enemy draws to be a (Attack:+0) instead.',
    count: 2,
    gold: 10,
    effects: '',
    when: { type: WHEN.ATTACKED },
    what: [{ type: WHAT.TREAT_CRIT_AS_POS0 }],
    after: AFTER.NONE,
    slot: SLOT.HEAD,
    type: TYPE.PROSPERITY,
    prosperity: 1,
  },
  [ID.HEATER_SHIELD]: {
    id: ID.HEATER_SHIELD,
    name: 'Heater Shield',
    desc: 'When damaged by an attack, gain (Symbol:Shield) 1 for the attack.',
    count: 2,
    gold: 20,
    effects: '',
    when: { type: WHEN.DAMAGED_BY_ATTACK },
    what: [{ type: WHAT.SHIELD, count: 1 }],
    after: AFTER.SPENT,
    slot: SLOT.ONE_HAND,
    type: TYPE.PROSPERITY,
    prosperity: 1,
  },
  [ID.PIERCING_BOW]: {
    id: ID.PIERCING_BOW,
    name: 'Piercing Bow',
    desc: 'During your ranged attack, ignore all Shield values for the entire Attack action.',
    count: 2,
    gold: 30,
    effects: '',
    when: { type: WHEN.ENTIRE_RANGED_ATTACK_ACTION },
    what: [{ type: WHAT.IGNORE_SHIELD }],
    after: AFTER.CONSUMED,
    slot: SLOT.TWO_HANDS,
    type: TYPE.PROSPERITY,
    prosperity: 1,
  },
  [ID.WAR_HAMMER]: {
    id: ID.WAR_HAMMER,
    name: 'War Hammer',
    desc: 'During your melee attack, add (Effect:Stun) to the entire Attack action.',
    count: 2,
    gold: 30,
    effects: '',
    when: { type: WHEN.ENTIRE_MELEE_ATTACK_ACTION },
    what: [{ type: WHAT.STUN }],
    after: AFTER.CONSUMED,
    slot: SLOT.TWO_HANDS,
    type: TYPE.PROSPERITY,
    prosperity: 1,
  },
  [ID.POISON_DAGGER]: {
    id: ID.POISON_DAGGER,
    name: 'Poison Dagger',
    desc: 'During your melee attack, add (Effect:Poison) to a single attack.',
    count: 2,
    gold: 20,
    effects: '',
    when: { type: WHEN.SINGLE_MELEE_ATTACK },
    what: [{ type: WHAT.POISON }],
    after: AFTER.SPENT,
    slot: SLOT.ONE_HAND,
    type: TYPE.PROSPERITY,
    prosperity: 1,
  },
  [ID.MINOR_HEALING_POTION]: {
    id: ID.MINOR_HEALING_POTION,
    name: 'Minor Healing Potion',
    desc: 'During your turn, perform a "(Symbol:Heal) 3, Self" action.',
    count: 4,
    gold: 10,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.HEAL, count: 3 }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.PROSPERITY,
    prosperity: 1,
  },
  [ID.MINOR_STAMINA_POTION]: {
    id: ID.MINOR_STAMINA_POTION,
    name: 'Minor Stamina Potion',
    desc: 'During your turn, (Symbol:Recover) up to two of your discarded cards.',
    count: 4,
    gold: 10,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.RECOVER_X_DISCARDED_CARDS, count: 2 }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.PROSPERITY,
    prosperity: 1,
  },
  [ID.MINOR_POWER_POTION]: {
    id: ID.MINOR_POWER_POTION,
    name: 'Minor Power Potion',
    desc: 'During your attack, add +1 (Symbol:Attack) to your entire Attack action.',
    count: 4,
    gold: 10,
    effects: '',
    when: { type: WHEN.ENTIRE_ATTACK_ACTION },
    what: [{ type: WHAT.ADD_X_ATTACK, count: 1 }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.PROSPERITY,
    prosperity: 1,
  },
  [ID.BOOTS_OF_SPEED]: {
    id: ID.BOOTS_OF_SPEED,
    name: 'Boots of Speed',
    desc:
      'At the beginning of a round, after all ability cards have been revealed, increase or decrease your leading initiative value by 10.',
    count: 2,
    gold: 30,
    effects: '',
    when: { type: WHEN.AFTER_ABILITY_CARDS_REVEALED },
    what: [{ type: WHAT.CHANGE_INITIATIVE_BY_X, count: 10 }],
    after: AFTER.SPENT,
    slot: SLOT.LEGS,
    type: TYPE.PROSPERITY,
    prosperity: 2,
  },
  [ID.CLOAK_OF_POCKETS]: {
    id: ID.CLOAK_OF_POCKETS,
    name: 'Cloak of Pockets',
    desc: 'You can carry two additional (Slot:Sm) Small items',
    count: 2,
    gold: 20,
    effects: '',
    when: { type: WHEN.EQUIPPED },
    what: [{ type: WHAT.ADD_X_SLOTS, count: 2, slot: SLOT.SMALL_ITEM }],
    after: AFTER.NONE,
    slot: SLOT.BODY,
    type: TYPE.PROSPERITY,
    prosperity: 2,
  },
  [ID.EMPOWERING_TALISMAN]: {
    id: ID.EMPOWERING_TALISMAN,
    name: 'Empowering Talisman',
    desc: 'During your turn, (Symbol:ItemRefresh) one of your consumed (Slot:Sm) Small items.',
    count: 2,
    gold: 45,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.REFRESH_X_CONSUMED_SLOT, count: 1, slot: SLOT.SMALL_ITEM }],
    after: AFTER.CONSUMED,
    slot: SLOT.HEAD,
    type: TYPE.PROSPERITY,
    prosperity: 2,
  },
  [ID.BATTLE_AXE]: {
    id: ID.BATTLE_AXE,
    name: 'Battle-Axe',
    desc: 'During your single-target melee attack action, turn the attack into the following: (Hex:Pattern:G1R3R)',
    count: 2,
    gold: 20,
    effects: '',
    when: { type: WHEN.SINGLE_MELEE_ATTACK },
    what: [{ type: WHAT.CLEAVE, count: 2 }],
    after: AFTER.CONSUMED,
    slot: SLOT.ONE_HAND,
    type: TYPE.PROSPERITY,
    prosperity: 2,
  },
  [ID.WEIGHTED_NET]: {
    id: ID.WEIGHTED_NET,
    name: 'Weighted Net',
    desc: 'During your ranged attack, add (Effect:Immobilize) to a single attack.',
    count: 2,
    gold: 20,
    effects: '',
    when: { type: WHEN.SINGLE_RANGED_ATTACK },
    what: [{ type: WHAT.IMMOBILIZE }],
    after: AFTER.SPENT,
    slot: SLOT.TWO_HANDS,
    type: TYPE.PROSPERITY,
    prosperity: 2,
  },
  [ID.MINOR_MANA_POTION]: {
    id: ID.MINOR_MANA_POTION,
    name: 'Minor Mana Potion',
    desc: 'During your turn, create (Element:Any)',
    count: 4,
    gold: 10,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.CREATE_X_ELEMENTS, count: 2 }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.PROSPERITY,
    prosperity: 2,
  },
  [ID.STUN_POWDER]: {
    id: ID.STUN_POWDER,
    name: 'Stun Powder',
    desc: 'During your attack, add (Effect:Stun) to a single attack.',
    count: 2,
    gold: 20,
    effects: '',
    when: { type: WHEN.SINGLE_ATTACK },
    what: [{ type: WHAT.STUN }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.PROSPERITY,
    prosperity: 2,
  },
  [ID.HEAVY_GREAVES]: {
    id: ID.HEAVY_GREAVES,
    name: 'Heavy Greaves',
    desc: 'You are immune to all forced movement caused by enemies or scenario effects.',
    count: 2,
    gold: 20,
    effects: '(Symbol:AttackNeg1) x1',
    when: { type: WHEN.EQUIPPED },
    what: [{ type: WHAT.IMMUNE_TO_FORCED_MOVEMENT }],
    after: AFTER.NONE,
    slot: SLOT.LEGS,
    type: TYPE.PROSPERITY,
    prosperity: 3,
  },
  [ID.CHAINMAIL]: {
    id: ID.CHAINMAIL,
    name: 'Chainmail',
    desc: 'On the next three sources of damage to you from attacks, gain (Symbol:Shield) 1.',
    count: 2,
    gold: 20,
    effects: '(Symbol:AttackNeg1) x3',
    when: { type: WHEN.NEXT_X_SOURCES_OF_DAMAGE, count: 3 },
    what: [{ type: WHAT.SHIELD, count: 1 }],
    after: AFTER.SPENT,
    slot: SLOT.BODY,
    type: TYPE.PROSPERITY,
    prosperity: 3,
  },
  [ID.AMULET_OF_LIFE]: {
    id: ID.AMULET_OF_LIFE,
    name: 'Amulet of Life',
    desc: 'During your turn, (Symbol:Heal) 1 damage.',
    count: 2,
    gold: 20,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.HEAL, count: 1 }],
    after: AFTER.SPENT,
    slot: SLOT.HEAD,
    type: TYPE.PROSPERITY,
    prosperity: 3,
  },
  [ID.JAGGED_SWORD]: {
    id: ID.JAGGED_SWORD,
    name: 'Jagged Sword',
    desc: 'During your melee attack, add (Effect:Wound) to a single attack.',
    count: 2,
    gold: 30,
    effects: '',
    when: { type: WHEN.SINGLE_MELEE_ATTACK },
    what: [{ type: WHAT.WOUND }],
    after: AFTER.SPENT,
    slot: SLOT.ONE_HAND,
    type: TYPE.PROSPERITY,
    prosperity: 3,
  },
  [ID.LONG_SPEAR]: {
    id: ID.LONG_SPEAR,
    name: 'Long Spear',
    desc: 'Turn a single-target melee attack into the following: (Hex:Pattern:G1R1R)',
    count: 2,
    gold: 30,
    effects: '',
    when: { type: WHEN.SINGLE_MELEE_ATTACK },
    what: [{ type: WHAT.PENETRATE, count: 2 }],
    after: AFTER.SPENT,
    slot: SLOT.TWO_HANDS,
    type: TYPE.PROSPERITY,
    prosperity: 3,
  },
  [ID.MAJOR_HEALING_POTION]: {
    id: ID.MAJOR_HEALING_POTION,
    name: 'Major Healing Potion',
    desc: 'During your turn, (Symbol:Heal) 5 damage.',
    count: 4,
    gold: 30,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.HEAL, count: 5 }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.PROSPERITY,
    prosperity: 3,
  },
  [ID.MOON_EARRING]: {
    id: ID.MOON_EARRING,
    name: 'Moon Earring',
    desc: 'During your turn, (Symbol:ItemRefresh) all of your spent items.',
    count: 2,
    gold: 20,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.REFRESH_SPENT_ITEMS }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.PROSPERITY,
    prosperity: 3,
  },
  [ID.COMFORTABLE_SHOES]: {
    id: ID.COMFORTABLE_SHOES,
    name: 'Comfortable Shoes',
    desc:
      'Whenever you use the default bottom of an ability card, perform a (Symbol:Move) 3 action instead of a (Symbol:Move) 2 action.',
    count: 2,
    gold: 30,
    effects: '',
    when: { type: WHEN.USE_DEFAULT_BOTTOM_ABILITY },
    what: [{ type: WHAT.MOVE, count: 3 }],
    after: AFTER.NONE,
    slot: SLOT.LEGS,
    type: TYPE.PROSPERITY,
    prosperity: 4,
  },
  [ID.STUDDED_LEATHER]: {
    id: ID.STUDDED_LEATHER,
    name: 'Studded Leather',
    desc: 'When attacked, the attacker gains Disadvantage on the attack and you gain (Symbol:Shield) 1 for the attack.',
    count: 2,
    gold: 30,
    effects: '',
    when: { type: WHEN.ATTACKED },
    what: [{ type: WHAT.ATTACKER_DISADVANTAGE }, { type: WHAT.SHIELD, count: 1 }],
    after: AFTER.SPENT,
    slot: SLOT.BODY,
    type: TYPE.PROSPERITY,
    prosperity: 4,
  },
  [ID.HAWK_HELM]: {
    id: ID.HAWK_HELM,
    name: 'Hawk Helm',
    desc: 'During your ranged attack, add +1 (Symbol:Range) to your entire Attack action.',
    count: 2,
    gold: 20,
    effects: '',
    when: { type: WHEN.ENTIRE_RANGED_ATTACK_ACTION },
    what: [{ type: WHAT.ADD_X_RANGE, count: 1 }],
    after: AFTER.SPENT,
    slot: SLOT.HEAD,
    type: TYPE.PROSPERITY,
    prosperity: 4,
  },
  [ID.TOWER_SHIELD]: {
    id: ID.TOWER_SHIELD,
    name: 'Tower Shield',
    desc: 'When damaged by an attack, gain (Symbol:Shield) 2 for the attack.',
    count: 2,
    gold: 40,
    effects: '',
    when: { type: WHEN.DAMAGED_BY_ATTACK },
    what: [{ type: WHAT.SHIELD, count: 2 }],
    after: AFTER.SPENT,
    slot: SLOT.ONE_HAND,
    type: TYPE.PROSPERITY,
    prosperity: 4,
  },
  [ID.VOLATILE_BOMB]: {
    id: ID.VOLATILE_BOMB,
    name: 'Volatile Bomb',
    desc: 'During your single-target ranged attack action, turn the attack into the following: (Hex:Pattern:R1R3R)',
    count: 2,
    gold: 30,
    effects: '',
    when: { type: WHEN.SINGLE_TARGET_RANGED_ATTACK },
    what: [{ type: WHAT.AOE, count: 3 }],
    after: AFTER.CONSUMED,
    slot: SLOT.ONE_HAND,
    type: TYPE.PROSPERITY,
    prosperity: 4,
  },
  [ID.MAJOR_STAMINA_POTION]: {
    id: ID.MAJOR_STAMINA_POTION,
    name: 'Major Stamina Potion',
    desc: 'During your turn, Recover up to three of your discarded cards.',
    count: 4,
    gold: 30,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.RECOVER_X_DISCARDED_CARDS, count: 3 }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.PROSPERITY,
    prosperity: 4,
  },
  [ID.FALCON_FIGURINE]: {
    id: ID.FALCON_FIGURINE,
    name: 'Falcon Figurine',
    desc: 'Summon (summon:JadeFalcon)',
    count: 2,
    gold: 50,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.SUMMON, summon: SUMMON.JADE_FALCON }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.PROSPERITY,
    prosperity: 4,
  },
  [ID.BOOTS_OF_DASHING]: {
    id: ID.BOOTS_OF_DASHING,
    name: 'Boots of Dashing',
    desc: 'During your movement, add +3 (Symbol:Move) to the movement.',
    count: 2,
    gold: 40,
    effects: '',
    when: { type: WHEN.MOVEMENT },
    what: [{ type: WHAT.ADD_X_MOVEMENT, count: 3 }],
    after: AFTER.SPENT,
    slot: SLOT.LEGS,
    type: TYPE.PROSPERITY,
    prosperity: 5,
  },
  [ID.ROBES_OF_EVOCATION]: {
    id: ID.ROBES_OF_EVOCATION,
    name: 'Robes of Evocation',
    desc: 'During your attack, (Element:Any:Consume) to add +1 (Symbol:Attack) to the entire Attack action.',
    count: 2,
    gold: 40,
    effects: '',
    when: { type: WHEN.ENTIRE_ATTACK_ACTION },
    what: [{ type: WHAT.CONSUME_ANY_ELEMENT }, { type: WHAT.ADD_X_ATTACK, count: 1 }],
    after: AFTER.SPENT,
    slot: SLOT.BODY,
    type: TYPE.PROSPERITY,
    prosperity: 5,
  },
  [ID.HEAVY_BASINET]: {
    id: ID.HEAVY_BASINET,
    name: 'Heavy Basinet',
    desc: 'You are immune to (Effect:Stun) and (Effect:Muddle).',
    count: 2,
    gold: 30,
    effects: '(Symbol:AttackNeg1) x2',
    when: { type: WHEN.EQUIPPED },
    what: [{ type: WHAT.IMMUNE_TO_STUN }, { type: WHAT.IMMUNE_TO_MUDDLE }],
    after: AFTER.NONE,
    slot: SLOT.HEAD,
    type: TYPE.PROSPERITY,
    prosperity: 5,
  },
  [ID.HOOKED_CHAIN]: {
    id: ID.HOOKED_CHAIN,
    name: 'Hooked Chain',
    desc: 'During your ranged attack, add (Effect:Pull) 2 to the entire Attack action.',
    count: 2,
    gold: 40,
    effects: '',
    when: { type: WHEN.ENTIRE_RANGED_ATTACK_ACTION },
    what: [{ type: WHAT.ADD_PULL, count: 2 }],
    after: AFTER.SPENT,
    slot: SLOT.TWO_HANDS,
    type: TYPE.PROSPERITY,
    prosperity: 5,
  },
  [ID.VERSATILE_DAGGER]: {
    id: ID.VERSATILE_DAGGER,
    name: 'Versatile Dagger',
    desc:
      'Whenever you use the default top of an ability card, perform an (Attack:+3) action instead of an (Attack:+2) action.',
    count: 2,
    gold: 25,
    effects: '',
    when: { type: WHEN.USE_DEFAULT_TOP_ABILITY },
    what: [{ type: WHAT.ATTACK, count: 3 }],
    after: AFTER.NONE,
    slot: SLOT.ONE_HAND,
    type: TYPE.PROSPERITY,
    prosperity: 5,
  },
  [ID.MAJOR_POWER_POTION]: {
    id: ID.MAJOR_POWER_POTION,
    name: 'Major Power Potion',
    desc: 'During your attack, add +2 (Symbol:Attack) to your entire Attack action.',
    count: 4,
    gold: 40,
    effects: '',
    when: { type: WHEN.ENTIRE_ATTACK_ACTION },
    what: [{ type: WHAT.ADD_X_ATTACK, count: 2 }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.PROSPERITY,
    prosperity: 5,
  },
  [ID.RING_OF_HASTE]: {
    id: ID.RING_OF_HASTE,
    name: 'Ring of Haste',
    desc:
      'At the end of your turn, play one card from your hand and immediately perform the bottom action of the card.',
    count: 2,
    gold: 30,
    effects: '',
    when: { type: WHEN.END_OF_TURN },
    what: [{ type: WHAT.PLAY_BOTTOM_ACTION_FROM_CARD_IN_HAND }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.PROSPERITY,
    prosperity: 5,
  },
  [ID.BOOTS_OF_QUICKNESS]: {
    id: ID.BOOTS_OF_QUICKNESS,
    name: 'Boots of Quickness',
    desc:
      'At the beginning of a round, after all ability cards have been revealed, increase or decrease your leading initiative value by 20.',
    count: 2,
    gold: 75,
    effects: '',
    when: { type: WHEN.AFTER_ABILITY_CARDS_REVEALED },
    what: [{ type: WHAT.CHANGE_INITIATIVE_BY_X, count: 20 }],
    after: AFTER.SPENT,
    slot: SLOT.LEGS,
    type: TYPE.PROSPERITY,
    prosperity: 6,
  },
  [ID.SPLINTMAIL]: {
    id: ID.SPLINTMAIL,
    name: 'Splintmail',
    desc: 'On the next four sources of damage to you from attacks, gain (Symbol:Shield) 1.',
    count: 2,
    gold: 35,
    effects: '',
    when: { type: WHEN.NEXT_X_SOURCES_OF_DAMAGE },
    what: [{ type: WHAT.SHIELD }],
    after: AFTER.SPENT,
    slot: SLOT.BODY,
    type: TYPE.PROSPERITY,
    prosperity: 6,
  },
  [ID.PENDANT_OF_DARK_PACTS]: {
    id: ID.PENDANT_OF_DARK_PACTS,
    name: 'Pendant of Dark Pacts',
    desc: 'During your turn, (Symbol:ItemRefresh) two of your consumed (Slot:Sm) Small items.\nGain (Effect:Curse).',
    count: 2,
    gold: 75,
    effects: '(Effect:Curse) x2',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.REFRESH_X_CONSUMED_SLOT, count: 2, slot: SLOT.SMALL_ITEM }],
    after: AFTER.CONSUMED,
    slot: SLOT.HEAD,
    type: TYPE.PROSPERITY,
    prosperity: 6,
  },
  [ID.SPIKED_SHIELD]: {
    id: ID.SPIKED_SHIELD,
    name: 'Spiked Shield',
    desc: 'When damaged by an attack, gain (Symbol:Shield) 1 and (Symbol:Retaliate) 2 for the attack.',
    count: 2,
    gold: 40,
    effects: '',
    when: { type: WHEN.DAMAGED_BY_ATTACK },
    what: [{ type: WHAT.SHIELD, count: 1 }, { type: WHAT.RETALIATE, count: 2 }],
    after: AFTER.SPENT,
    slot: SLOT.ONE_HAND,
    type: TYPE.PROSPERITY,
    prosperity: 6,
  },
  [ID.REAPING_SCYTHE]: {
    id: ID.REAPING_SCYTHE,
    name: 'Reaping Scythe',
    desc: 'Turn a single-target melee attack into the following: (Hex:Pattern:G1R3R4R)',
    count: 2,
    gold: 40,
    effects: '',
    when: { type: WHEN.SINGLE_TARGET_MELEE_ATTACK },
    what: [{ type: WHAT.CLEAVE, count: 3 }],
    after: AFTER.CONSUMED,
    slot: SLOT.TWO_HANDS,
    type: TYPE.PROSPERITY,
    prosperity: 6,
  },
  [ID.MAJOR_MANA_POTION]: {
    id: ID.MAJOR_MANA_POTION,
    name: 'Major Mana Potion',
    desc: 'During your turn, create two (Element:Any).',
    count: 4,
    gold: 30,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.CREATE_X_ELEMENTS, count: 2 }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.PROSPERITY,
    prosperity: 6,
  },
  [ID.SUN_EARRING]: {
    id: ID.SUN_EARRING,
    name: 'Sun Earring',
    desc: 'During your turn, (Symbol:ItemRefresh) all of your spent items and (Symbol:Heal) 3 damage.',
    count: 2,
    gold: 40,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.REFRESH_SPENT_ITEMS }, { type: WHAT.HEAL, count: 3 }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.PROSPERITY,
    prosperity: 6,
  },
  [ID.STEEL_SABATONS]: {
    id: ID.STEEL_SABATONS,
    name: 'Steel Sabatons',
    desc: 'If you move 1 or fewer hexes on your turn, gain (Symbol:Shield) 1 for the round.',
    count: 2,
    gold: 60,
    effects: '(Symbol:AttackNeg1) x2',
    when: { type: WHEN.MOVE_X_OR_LESS, count: 1 },
    what: [{ type: WHAT.SHIELD, count: 1 }],
    after: AFTER.NONE,
    slot: SLOT.LEGS,
    type: TYPE.PROSPERITY,
    prosperity: 7,
  },
  [ID.SHADOW_ARMOR]: {
    id: ID.SHADOW_ARMOR,
    name: 'Shadow Armor',
    desc: 'When you are damaged by an attack, suffer no damage instead.',
    count: 2,
    gold: 30,
    effects: '',
    when: { type: WHEN.DAMAGED_BY_ATTACK },
    what: [{ type: WHAT.SUFFER_NO_DAMAGE }],
    after: AFTER.CONSUMED,
    slot: SLOT.BODY,
    type: TYPE.PROSPERITY,
    prosperity: 7,
  },
  [ID.PROTECTIVE_CHARM]: {
    id: ID.PROTECTIVE_CHARM,
    name: 'Protective Charm',
    desc: 'You are immune to (Effect:Poison) and (Effect:Wound).',
    count: 2,
    gold: 60,
    effects: '',
    when: { type: WHEN.EQUIPPED },
    what: [{ type: WHAT.IMMUNE_TO_POISON }, { type: WHAT.IMMUNE_TO_WOUND }],
    after: AFTER.NONE,
    slot: SLOT.HEAD,
    type: TYPE.PROSPERITY,
    prosperity: 7,
  },
  [ID.BLACK_KNIFE]: {
    id: ID.BLACK_KNIFE,
    name: 'Black Knife',
    desc: 'During your melee attack, add (Effect:Curse) to a single attack.',
    count: 2,
    gold: 25,
    effects: '',
    when: { type: WHEN.SINGLE_MELEE_ATTACK },
    what: [{ type: WHAT.CURSE }],
    after: AFTER.SPENT,
    slot: SLOT.ONE_HAND,
    type: TYPE.PROSPERITY,
    prosperity: 7,
  },
  [ID.STAFF_OF_EMINENCE]: {
    id: ID.STAFF_OF_EMINENCE,
    name: 'Staff of Eminence',
    desc: 'During your ranged attack, (Element:Any) to add +1 (Symbol:Attack) to the entire Attack action.',
    count: 2,
    gold: 60,
    effects: '',
    when: { type: WHEN.ENTIRE_RANGED_ATTACK_ACTION },
    what: [{ type: WHAT.CONSUME_ANY_ELEMENT }, { type: WHAT.ADD_X_ATTACK, count: 1 }],
    after: AFTER.SPENT,
    slot: SLOT.TWO_HANDS,
    type: TYPE.PROSPERITY,
    prosperity: 7,
  },
  [ID.SUPER_HEALING_POTION]: {
    id: ID.SUPER_HEALING_POTION,
    name: 'Super Healing Potion',
    desc: 'During your turn, (Symbol:Heal) 7 damage.',
    count: 4,
    gold: 50,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.HEAL, count: 7 }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.PROSPERITY,
    prosperity: 7,
  },
  [ID.RING_OF_BRUTALITY]: {
    id: ID.RING_OF_BRUTALITY,
    name: 'Ring of Brutality',
    desc: 'At the end of your turn, play one card from your hand and immediately perform the top action of the card.',
    count: 2,
    gold: 40,
    effects: '',
    when: { type: WHEN.END_OF_TURN },
    what: [{ type: WHAT.PLAY_TOP_ACTION_FROM_CARD_IN_HAND }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.PROSPERITY,
    prosperity: 7,
  },
  [ID.SERENE_SANDALS]: {
    id: ID.SERENE_SANDALS,
    name: 'Serene Sandals',
    desc:
      'Whenever you use the default bottom of an ability card perform a (Symbol:Move) 4 action instead of a (Symbol:Move) 2 action.',
    count: 2,
    gold: 75,
    effects: '',
    when: { type: WHEN.USE_DEFAULT_BOTTOM_ABILITY },
    what: [{ type: WHAT.MOVE, count: 4 }],
    after: AFTER.NONE,
    slot: SLOT.LEGS,
    type: TYPE.PROSPERITY,
    prosperity: 8,
  },
  [ID.CLOAK_OF_PHASING]: {
    id: ID.CLOAK_OF_PHASING,
    name: 'Cloak of Phasing',
    desc: 'Gain flying. While occupying an obstacle hex, you are considered Invisible and cannot attack',
    count: 2,
    gold: 75,
    effects: '',
    when: { type: WHEN.EQUIPPED },
    what: [{ type: WHAT.FLYING }, { type: WHAT.PHASING }],
    after: AFTER.NONE,
    slot: SLOT.BODY,
    type: TYPE.PROSPERITY,
    prosperity: 8,
  },
  [ID.TELESCOPIC_LENS]: {
    id: ID.TELESCOPIC_LENS,
    name: 'Telescopic Lens',
    desc: 'During your ranged attack, add +2 (Symbol:Range) to your entire Attack action.',
    count: 2,
    gold: 50,
    effects: '',
    when: { type: WHEN.ENTIRE_RANGED_ATTACK_ACTION },
    what: [{ type: WHAT.ADD_X_RANGE, count: 2 }],
    after: AFTER.SPENT,
    slot: SLOT.HEAD,
    type: TYPE.PROSPERITY,
    prosperity: 8,
  },
  [ID.UNSTABLE_EXPLOSIVES]: {
    id: ID.UNSTABLE_EXPLOSIVES,
    name: 'Unstable Explosives',
    desc:
      'Turn a single target ranged attack into the following: (Hex:Pattern:R1R3R1R). All allies in the attack area suffer 3 damage.',
    count: 2,
    gold: 45,
    effects: '',
    when: { type: WHEN.SINGLE_RANGED_ATTACK },
    what: [{ type: WHAT.AOE, count: 4 }],
    after: AFTER.CONSUMED,
    slot: SLOT.ONE_HAND,
    type: TYPE.PROSPERITY,
    prosperity: 8,
  },
  [ID.WALL_SHIELD]: {
    id: ID.WALL_SHIELD,
    name: 'Wall Shield',
    desc: 'When damaged by an attack, gain (Symbol:Shield) 4 for the attack.',
    count: 2,
    gold: 60,
    effects: '',
    when: { type: WHEN.DAMAGED_BY_ATTACK },
    what: [{ type: WHAT.SHIELD, count: 4 }],
    after: AFTER.SPENT,
    slot: SLOT.TWO_HANDS,
    type: TYPE.PROSPERITY,
    prosperity: 8,
  },
  [ID.DOOM_POWDER]: {
    id: ID.DOOM_POWDER,
    name: 'Doom Powder',
    desc: 'During your attack, add (Effect:Stun), (Effect:Poison), and (Effect:Curse) to a single attack.',
    count: 2,
    gold: 40,
    effects: '',
    when: { type: WHEN.SINGLE_ATTACK },
    what: [{ type: WHAT.STUN }, { type: WHAT.POISON }, { type: WHAT.CURSE }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.PROSPERITY,
    prosperity: 8,
  },
  [ID.LUCKY_EYE]: {
    id: ID.LUCKY_EYE,
    name: 'Lucky Eye',
    desc: 'During your turn, (Effect:Strengthen) yourself and all adjacent allies.',
    count: 2,
    gold: 60,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.STRENGTHEN_YOURSELF_AND_ADJACENT_ALLIES }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.PROSPERITY,
    prosperity: 8,
  },
  [ID.BOOTS_OF_SPRINTING]: {
    id: ID.BOOTS_OF_SPRINTING,
    name: 'Boots of Sprinting',
    desc: 'During your movement, add +4 (Symbol:Move) to the movement.',
    count: 2,
    gold: 75,
    effects: '',
    when: { type: WHEN.MOVEMENT },
    what: [{ type: WHAT.ADD_X_MOVEMENT, count: 4 }],
    after: AFTER.SPENT,
    slot: SLOT.LEGS,
    type: TYPE.PROSPERITY,
    prosperity: 9,
  },
  [ID.PLATEMAIL]: {
    id: ID.PLATEMAIL,
    name: 'Platemail',
    desc: 'On the next five sources of damage to you from attacks, gain (Symbol:Shield) 1.',
    count: 2,
    gold: 50,
    effects: '(Symbol:AttackNeg1) x5',
    when: { type: WHEN.NEXT_X_SOURCES_OF_DAMAGE, count: 5 },
    what: [{ type: WHAT.SHIELD, count: 1 }],
    after: AFTER.SPENT,
    slot: SLOT.BODY,
    type: TYPE.PROSPERITY,
    prosperity: 9,
  },
  [ID.MASK_OF_TERROR]: {
    id: ID.MASK_OF_TERROR,
    name: 'Mask of Terror',
    desc: 'During your melee attack, add (Effect:Push) 1.',
    count: 2,
    gold: 50,
    effects: '',
    when: { type: WHEN.ENTIRE_MELEE_ATTACK_ACTION },
    what: [{ type: WHAT.PUSH, count: 1 }],
    after: AFTER.NONE, // TODO: Get confirmation that this card applies to all melee attacks while equipped
    slot: SLOT.HEAD,
    type: TYPE.PROSPERITY,
    prosperity: 9,
  },
  [ID.BALANCED_BLADE]: {
    id: ID.BALANCED_BLADE,
    name: 'Balanced Blade',
    desc:
      'Whenever you use the default top of an ability card, perform an (Attack:+4) instead of an (Attack:+2) action.',
    count: 2,
    gold: 60,
    effects: '',
    when: { type: WHEN.USE_DEFAULT_TOP_ABILITY },
    what: [{ type: WHAT.ATTACK, count: 4 }],
    after: AFTER.NONE,
    slot: SLOT.ONE_HAND,
    type: TYPE.PROSPERITY,
    prosperity: 9,
  },
  [ID.HALBERD]: {
    id: ID.HALBERD,
    name: 'Halberd',
    desc: 'During your single target melee attack, you can attack and single enemy within 2 hexes.',
    count: 2,
    gold: 75,
    effects: '',
    when: { type: WHEN.SINGLE_TARGET_MELEE_ATTACK },
    what: [{ type: WHAT.ADD_X_RANGE, count: 1 }],
    after: AFTER.NONE,
    slot: SLOT.TWO_HANDS,
    type: TYPE.PROSPERITY,
    prosperity: 9,
  },
  [ID.STAR_EARRING]: {
    id: ID.STAR_EARRING,
    name: 'Star Earring',
    desc:
      'During your turn, (Symbol:ItemRefresh) all of your spent items, (Symbol:Heal) 3 damage, and Recover up to two of your discarded cards.',
    count: 2,
    gold: 70,
    effects: '',
    when: { type: WHEN.TURN },
    what: [
      { type: WHAT.REFRESH_SPENT_ITEMS },
      { type: WHAT.HEAL, count: 3 },
      { type: WHAT.RECOVER_X_DISCARDED_CARDS, count: 2 },
    ],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.PROSPERITY,
    prosperity: 9,
  },
  [ID.SECOND_CHANCE_RING]: {
    id: ID.SECOND_CHANCE_RING,
    name: 'Second Chance Ring',
    desc:
      'At the end of your turn, play two cards from your hand and perform an additional turn this round based on your new leading initiative (which must be later than your previous initiative).',
    count: 2,
    gold: 75,
    effects: '',
    when: { type: WHEN.END_OF_TURN },
    what: [{ type: WHAT.PLAY_ANOTHER_TURN, count: 'Must be later than previous initiative.' }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.PROSPERITY,
    prosperity: 9,
  },
  [ID.BOOTS_OF_LEVITATION]: {
    id: ID.BOOTS_OF_LEVITATION,
    name: 'Boots of Levitation',
    desc: 'Gain flying',
    count: 2,
    gold: 50,
    effects: '',
    when: { type: WHEN.EQUIPPED },
    what: [{ type: WHAT.FLYING }],
    after: AFTER.NONE,
    slot: SLOT.LEGS,
    type: TYPE.RANDOM,
  },
  [ID.SHOES_OF_HAPPINESS]: {
    id: ID.SHOES_OF_HAPPINESS,
    name: 'Shoes of Happiness',
    desc: 'If you move 6 or more hexes on your turn, gain 1 experience.',
    count: 2,
    gold: 50,
    effects: '',
    when: { type: WHEN.MOVE_X_OR_MORE, count: 6 },
    what: [{ type: WHAT.XP, count: 1 }],
    after: AFTER.NONE,
    slot: SLOT.LEGS,
    type: TYPE.RANDOM,
  },
  [ID.BLINKING_CAPE]: {
    id: ID.BLINKING_CAPE,
    name: 'Blinking Cape',
    desc: 'During your turn, perform a "(Symbol:Move) 4, (Symbol:Jump)" action',
    count: 2,
    gold: 50,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.MOVE, count: 4 }, { type: WHAT.JUMP }],
    after: AFTER.CONSUMED,
    slot: SLOT.BODY,
    type: TYPE.RANDOM,
  },
  [ID.SWORDEDGE_ARMOR]: {
    id: ID.SWORDEDGE_ARMOR,
    name: 'Swordedge Armor',
    desc:
      'On the next three sources of damage from attacks targeting you, gain (Symbol:Shield) 1, (Symbol:Retaliate) 1',
    count: 2,
    gold: 40,
    effects: '(Symbol:AttackNeg1) x4',
    when: { type: WHEN.NEXT_X_SOURCES_OF_DAMAGE, count: 3 },
    what: [{ type: WHAT.SHIELD, count: 1 }, { type: WHAT.RETALIATE, count: 1 }],
    after: AFTER.SPENT,
    slot: SLOT.BODY,
    type: TYPE.RANDOM,
  },
  [ID.CIRCLET_OF_ELEMENTS]: {
    id: ID.CIRCLET_OF_ELEMENTS,
    name: 'Circlet of Elements',
    desc: 'During your turn, (Element:Any:Consume) to create (Element:Any)',
    count: 2,
    gold: 25,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.CONSUME_ANY_ELEMENT }, { type: WHAT.CREATE_X_ELEMENTS, count: 1 }],
    after: AFTER.SPENT,
    slot: SLOT.HEAD,
    type: TYPE.RANDOM,
  },
  [ID.CHAIN_HOOD]: {
    id: ID.CHAIN_HOOD,
    name: 'Chain Hood',
    desc: 'While you are adjacent to three or more monsters, gain (Symbol:Shield) 1',
    count: 2,
    gold: 40,
    effects: '(Symbol:AttackNeg1) x1',
    when: { type: WHEN.ADJACENT_TO_X_ENEMIES, count: 3 },
    what: [{ type: WHAT.SHIELD, count: 1 }],
    after: AFTER.NONE,
    slot: SLOT.HEAD,
    type: TYPE.RANDOM,
  },
  [ID.FRIGID_BLADE]: {
    id: ID.FRIGID_BLADE,
    name: 'Frigid Blade',
    desc: 'During your melee attack, (Element:Ice:Consume) to add (Attack:+2) to a single attack.',
    count: 2,
    gold: 30,
    effects: '',
    when: { type: WHEN.SINGLE_MELEE_ATTACK },
    what: [{ type: WHAT.CONSUME_ELEMENT, element: ELEMENT.ICE }, { type: WHAT.ADD_X_ATTACK, count: 2 }],
    after: AFTER.NONE,
    slot: SLOT.ONE_HAND,
    type: TYPE.RANDOM,
  },
  [ID.STORM_BLADE]: {
    id: ID.STORM_BLADE,
    name: 'Storm Blade',
    desc: 'During your melee attack, (Element:Air:Consume) to add (Attack:+2) to a single attack.',
    count: 2,
    gold: 30,
    effects: '',
    when: { type: WHEN.SINGLE_MELEE_ATTACK },
    what: [{ type: WHAT.CONSUME_ELEMENT, element: ELEMENT.WIND }, { type: WHAT.ADD_X_ATTACK, count: 2 }],
    after: AFTER.NONE,
    slot: SLOT.ONE_HAND,
    type: TYPE.RANDOM,
  },
  [ID.INFERNO_BLADE]: {
    id: ID.INFERNO_BLADE,
    name: 'Inferno Blade',
    desc: 'During your melee attack, (Element:Fire:Consume) to add (Attack:+2) to a single attack.',
    count: 2,
    gold: 30,
    effects: '',
    when: { type: WHEN.SINGLE_MELEE_ATTACK },
    what: [{ type: WHAT.CONSUME_ELEMENT, element: ELEMENT.FIRE }, { type: WHAT.ADD_X_ATTACK, count: 2 }],
    after: AFTER.NONE,
    slot: SLOT.ONE_HAND,
    type: TYPE.RANDOM,
  },
  [ID.TREMOR_BLADE]: {
    id: ID.TREMOR_BLADE,
    name: 'Tremor Blade',
    desc: 'During your melee attack, (Element:Earth:Consume) to add (Attack:+2) to a single attack.',
    count: 2,
    gold: 30,
    effects: '',
    when: { type: WHEN.SINGLE_MELEE_ATTACK },
    what: [{ type: WHAT.CONSUME_ELEMENT, element: ELEMENT.EARTH }, { type: WHAT.ADD_X_ATTACK, count: 2 }],
    after: AFTER.NONE,
    slot: SLOT.ONE_HAND,
    type: TYPE.RANDOM,
  },
  [ID.BRILLIANT_BLADE]: {
    id: ID.BRILLIANT_BLADE,
    name: 'Brilliant Blade',
    desc: 'During your melee attack, (Element:Light:Consume) to add (Attack:+2) to a single attack.',
    count: 2,
    gold: 30,
    effects: '',
    when: { type: WHEN.SINGLE_MELEE_ATTACK },
    what: [{ type: WHAT.CONSUME_ELEMENT, element: ELEMENT.LIGHT }, { type: WHAT.ADD_X_ATTACK, count: 2 }],
    after: AFTER.NONE,
    slot: SLOT.ONE_HAND,
    type: TYPE.RANDOM,
  },
  [ID.NIGHT_BLADE]: {
    id: ID.NIGHT_BLADE,
    name: 'Night Blade',
    desc: 'During your melee attack, (Element:Dark:Consume) to add (Attack:+2) to a single attack.',
    count: 2,
    gold: 30,
    effects: '',
    when: { type: WHEN.SINGLE_MELEE_ATTACK },
    what: [{ type: WHAT.CONSUME_ELEMENT, element: ELEMENT.DARK }, { type: WHAT.ADD_X_ATTACK, count: 2 }],
    after: AFTER.NONE,
    slot: SLOT.ONE_HAND,
    type: TYPE.RANDOM,
  },
  [ID.WAND_OF_FROST]: {
    id: ID.WAND_OF_FROST,
    name: 'Wand of Frost',
    desc: 'During your turn, create (Element:Ice).',
    count: 2,
    gold: 30,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.CREATE_ELEMENT, element: ELEMENT.ICE }],
    after: AFTER.NONE,
    slot: SLOT.ONE_HAND,
    type: TYPE.RANDOM,
  },
  [ID.WAND_OF_STORMS]: {
    id: ID.WAND_OF_STORMS,
    name: 'Wand of Storms',
    desc: 'During your turn, create (Element:Air).',
    count: 2,
    gold: 30,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.CREATE_ELEMENT, element: ELEMENT.AIR }],
    after: AFTER.NONE,
    slot: SLOT.ONE_HAND,
    type: TYPE.RANDOM,
  },
  [ID.WAND_OF_INFERNOS]: {
    id: ID.WAND_OF_INFERNOS,
    name: 'Wand of Infernos',
    desc: 'During your turn, create (Element:Fire).',
    count: 2,
    gold: 30,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.CREATE_ELEMENT, element: ELEMENT.FIRE }],
    after: AFTER.NONE,
    slot: SLOT.ONE_HAND,
    type: TYPE.RANDOM,
  },
  [ID.WAND_OF_TREMORS]: {
    id: ID.WAND_OF_TREMORS,
    name: 'Wand of Tremors',
    desc: 'During your turn, create (Element:Earth).',
    count: 2,
    gold: 30,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.CREATE_ELEMENT, element: ELEMENT.EARTH }],
    after: AFTER.NONE,
    slot: SLOT.ONE_HAND,
    type: TYPE.RANDOM,
  },
  [ID.WAND_OF_BRILLIANCE]: {
    id: ID.WAND_OF_BRILLIANCE,
    name: 'Wand of Brilliance',
    desc: 'During your turn, create (Element:Light).',
    count: 2,
    gold: 30,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.CREATE_ELEMENT, element: ELEMENT.LIGHT }],
    after: AFTER.NONE,
    slot: SLOT.ONE_HAND,
    type: TYPE.RANDOM,
  },
  [ID.WAND_OF_DARKNESS]: {
    id: ID.WAND_OF_DARKNESS,
    name: 'Wand of Darkness',
    desc: 'During your turn, create (Element:Dark).',
    count: 2,
    gold: 30,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.CREATE_ELEMENT, element: ELEMENT.DARK }],
    after: AFTER.NONE,
    slot: SLOT.ONE_HAND,
    type: TYPE.RANDOM,
  },
  [ID.MINOR_CURE_POTION]: {
    id: ID.MINOR_CURE_POTION,
    name: 'Minor Cure Potion',
    desc: 'During your turn, remove one negative condition on yourself. This can be used while you have (Effect:Stun).',
    count: 2,
    gold: 10,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.REMOVE_NEGATIVE_CONDITION_SELF, note: 'This can be used while stunned.' }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.RANDOM,
  },
  [ID.MAJOR_CURE_POTION]: {
    id: ID.MAJOR_CURE_POTION,
    name: 'Major Cure Potion',
    desc:
      'During your turn, remove all negative conditions on yourself. This can be used while you have (Effect:Stun).',
    count: 2,
    gold: 30,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.REMOVE_ALL_NEGATIVE_CONDITIONS_SELF, note: 'This can be used while stunned.' }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.RANDOM,
  },
  [ID.STEEL_RING]: {
    id: ID.STEEL_RING,
    name: 'Steel Ring',
    desc: 'When damaged by an attack targeting you, gain (Symbol:Shield) 4 for the attack.',
    count: 2,
    gold: 20,
    effects: '',
    when: { type: WHEN.DAMAGED_BY_ATTACK },
    what: [{ type: WHAT.SHIELD, count: 4 }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.RANDOM,
  },
  [ID.DAMPENING_RING]: {
    id: ID.DAMPENING_RING,
    name: 'Dampening Ring',
    desc: 'Before an enemy would consume an element, consume that element instead for no effect',
    count: 2,
    gold: 25,
    effects: '',
    when: { type: WHEN.BEFORE_ENEMY_CONSUMES_ELEMENT },
    what: [{ type: WHAT.CONSUME_ANY_ELEMENT }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.RANDOM,
  },
  [ID.SCROLL_OF_POWER]: {
    id: ID.SCROLL_OF_POWER,
    name: 'Scroll of Power',
    desc: "During an ally's attack, add +1 (Symbol:Attack) to their entire attack action",
    count: 2,
    gold: 30,
    effects: '',
    when: { type: WHEN.ENTIRE_ALLY_ATTACK_ACTION },
    what: [{ type: WHAT.ADD_X_ATTACK, count: 1 }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.RANDOM,
  },
  [ID.SCROLL_OF_HEALING]: {
    id: ID.SCROLL_OF_HEALING,
    name: 'Scroll of Healing',
    desc: 'During your turn, perform a "(Symbol:Heal) 3, (Symbol:Range) 5" action',
    count: 2,
    gold: 30,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.HEAL, count: 3, range: 5 }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.RANDOM,
  },
  [ID.SCROLL_OF_STAMINA]: {
    id: ID.SCROLL_OF_STAMINA,
    name: 'Scroll of Stamina',
    desc: 'During your turn, an ally within (Symbol:Range) 5 may recover up to two of their discarded cards',
    count: 2,
    gold: 50,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.ALLY_WITHIN_X_RECOVER_Y_DISCARDED_CARDS, range: 5, count: 2 }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.RANDOM,
  },
  [ID.ROCKET_BOOTS]: {
    id: ID.ROCKET_BOOTS,
    name: 'Rocket Boots',
    desc: 'During your movement, add +3 (Symbol:Move) and (Symbol:Jump) to a single movement',
    count: 2,
    gold: 80,
    effects: '',
    when: { type: WHEN.MOVEMENT },
    what: [{ type: WHAT.ADD_X_MOVEMENT, count: 3 }, { type: WHAT.JUMP }],
    after: AFTER.SPENT,
    slot: SLOT.LEGS,
    type: TYPE.OTHER,
  },
  [ID.ENDURANCE_FOOTWRAPS]: {
    id: ID.ENDURANCE_FOOTWRAPS,
    name: 'Endurance Footwraps',
    desc: 'If you move 4 or more hexes on your turn, perform a "(Symbol:Heal) 1, Self" action.',
    count: 1,
    gold: 40,
    effects: '',
    when: { type: WHEN.MOVE_X_OR_MORE, count: 4 },
    what: [{ type: WHAT.HEAL, count: 1 }],
    after: AFTER.NONE,
    slot: SLOT.LEGS,
    type: TYPE.OTHER,
  },
  [ID.DRAKESCALE_BOOTS]: {
    id: ID.DRAKESCALE_BOOTS,
    name: 'Drakescale Boots',
    desc: 'You are unaffected by difficult and hazardous terrain.',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.EQUIPPED },
    what: [{ type: WHAT.IMMUNE_TO_TERRAIN }],
    after: AFTER.NONE,
    slot: SLOT.LEGS,
    type: TYPE.OTHER,
  },
  [ID.MAGMA_WADERS]: {
    id: ID.MAGMA_WADERS,
    name: 'Magma Waders',
    desc:
      'Ignore the damaging effects of hazardous terrain and perform a "(Symbol:Heal) 2, Self" action on any turn in which you have entered a hazardous terrain hex.',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.ENTER_HAZARDOUS_TERRAIN },
    what: [{ type: WHAT.IMMUNE_TO_TERRAIN }, { type: WHAT.HEAL, count: 2 }],
    after: AFTER.NONE,
    slot: SLOT.LEGS,
    type: TYPE.OTHER,
  },
  [ID.ROBES_OF_SUMMONING]: {
    id: ID.ROBES_OF_SUMMONING,
    name: 'Robes of Summoning',
    desc: 'During your turn, perform a "(Symbol:Heal) 2, target any summoned ally" action.',
    count: 1,
    gold: 40,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.HEAL_SUMMON, count: 2 }],
    after: AFTER.SPENT,
    slot: SLOT.BODY,
    type: TYPE.OTHER,
  },
  [ID.SECOND_SKIN]: {
    id: ID.SECOND_SKIN,
    name: 'Second Skin',
    desc: 'Remove two (Attack:-1) from your attack modifier deck.',
    count: 1,
    gold: 30,
    effects: '(Symbol:AttackNeg1) x2',
    when: { type: WHEN.EQUIPPED },
    what: [],
    after: AFTER.NONE,
    slot: SLOT.BODY,
    type: TYPE.OTHER,
  },
  [ID.SACRIFICIAL_ROBES]: {
    id: ID.SACRIFICIAL_ROBES,
    name: 'Sacrificial Robes',
    desc: 'During your ranged attack, suffer 3 damage to add +1 (Symbol:Attack) to the entire Attack action.',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.ENTIRE_RANGED_ATTACK_ACTION },
    what: [{ type: WHAT.SUFFER_DAMAGE, count: 3 }, { type: WHAT.ADD_X_ATTACK, count: 1 }],
    after: AFTER.CONSUMED,
    slot: SLOT.BODY,
    type: TYPE.OTHER,
  },
  [ID.DRAKESCALE_ARMOR]: {
    id: ID.DRAKESCALE_ARMOR,
    name: 'Drakescale Armor',
    desc: 'You are immune to (Effect:Poison) and (Effect:Wound).',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.EQUIPPED },
    what: [{ type: WHAT.IMMUNE_TO_POISON }, { type: WHAT.IMMUNE_TO_WOUND }],
    after: AFTER.NONE,
    slot: SLOT.BODY,
    type: TYPE.OTHER,
  },
  [ID.STEAM_ARMOR]: {
    id: ID.STEAM_ARMOR,
    name: 'Steam Armor',
    desc: 'On the next five sources of damage from attacks targeting you, gain (Symbol:Shield) 1.',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.NEXT_X_SOURCES_OF_DAMAGE },
    what: [{ type: WHAT.SHIELD, count: 1 }],
    after: AFTER.CONSUMED,
    slot: SLOT.BODY,
    type: TYPE.OTHER,
  },
  [ID.FLEA_BITTEN_SHAWL]: {
    id: ID.FLEA_BITTEN_SHAWL,
    name: 'Flea-Bitten Shawl',
    desc: 'You are considered to have an initiative of 99 for the purpose of enemy focusing.',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.EQUIPPED },
    what: [{ type: WHAT.PERCEIVED_INITIATIVE, count: 99 }],
    after: AFTER.NONE,
    slot: SLOT.BODY,
    type: TYPE.OTHER,
  },
  [ID.NECKLACE_OF_TEETH]: {
    id: ID.NECKLACE_OF_TEETH,
    name: 'Necklace of Teeth',
    desc: 'Any time you kill an enemy during your turn, perform a "(Symbol:Heal) 1, Self" action.',
    count: 1,
    gold: 40,
    effects: '',
    when: { type: WHEN.KILL_ENEMY },
    what: [{ type: WHAT.HEAL, count: 1 }],
    after: AFTER.NONE,
    slot: SLOT.HEAD,
    type: TYPE.OTHER,
  },
  [ID.HORNED_HELM]: {
    id: ID.HORNED_HELM,
    name: 'Horned Helm',
    desc: 'After moving 4 or more hexes on your turn, add +1 (Symbol:Attack) to your next melee attack this turn.',
    count: 1,
    gold: 30,
    effects: '',
    when: { type: WHEN.MOVE_X_OR_MORE, count: 4 },
    what: [{ type: WHAT.ADD_X_ATTACK, count: 1, note: 'Next attack only.' }],
    after: AFTER.NONE,
    slot: SLOT.HEAD,
    type: TYPE.OTHER,
  },
  [ID.DRAKESCALE_HELM]: {
    id: ID.DRAKESCALE_HELM,
    name: 'Drakescale Helm',
    desc: 'Whenever you gain (Effect:Muddle), gain (Effect:Strengthen) instead.',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.GAINING_MUDDLE },
    what: [{ type: WHAT.STRENGTHEN }],
    after: AFTER.NONE,
    slot: SLOT.HEAD,
    type: TYPE.OTHER,
  },
  [ID.THIEFS_HOOD]: {
    id: ID.THIEFS_HOOD,
    name: "Thief's Hood",
    desc: 'During your "(Symbol:Loot) 1" ability, perform a "(Symbol:Loot) 2" ability instead.',
    count: 1,
    gold: 20,
    effects: '',
    when: { type: WHEN.LOOT, range: 1 },
    what: [{ type: WHAT.LOOT, range: 2 }],
    after: AFTER.CONSUMED,
    slot: SLOT.HEAD,
    type: TYPE.OTHER,
  },
  [ID.HELM_OF_THE_MOUNTAIN]: {
    id: ID.HELM_OF_THE_MOUNTAIN,
    name: 'Helm of the Mountain',
    desc: 'When attacked, if (Element:Earth) is Strong, (Effect:Immobilize) the attacker.',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.ATTACKED_AND_ELEMENT_IS_STRONG, element: ELEMENT.EARTH },
    what: [{ type: WHAT.ATTACKER_IMMOBILIZE }],
    after: AFTER.NONE,
    slot: SLOT.HEAD,
    type: TYPE.OTHER,
  },
  [ID.WAVE_CREST]: {
    id: ID.WAVE_CREST,
    name: 'Wave Crest',
    desc: 'When attacked, if (Element:Ice) is Strong, perform a "(Effect:Push) 2" action targeting the attacker.',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.ATTACKED_AND_ELEMENT_IS_STRONG, element: ELEMENT.ICE },
    what: [{ type: WHAT.ATTACKER_PUSH, count: 2 }],
    after: AFTER.NONE,
    slot: SLOT.HEAD,
    type: TYPE.OTHER,
  },
  [ID.ANCIENT_DRILL]: {
    id: ID.ANCIENT_DRILL,
    name: 'Ancient Drill',
    desc: 'During your melee attack, add +2 (Symbol:Attack) and (Effect:Pierce) 2 to the entire Attack action',
    count: 1,
    gold: 30,
    effects: '',
    when: { type: WHEN.ENTIRE_MELEE_ATTACK_ACTION },
    what: [{ type: WHAT.ADD_X_ATTACK, count: 2 }, { type: WHAT.ADD_X_PIERCE, count: 2 }],
    after: AFTER.CONSUMED,
    slot: SLOT.TWO_HANDS,
    type: TYPE.OTHER,
  },
  [ID.SKULLBANE_AXE]: {
    id: ID.SKULLBANE_AXE,
    name: 'Skullbane Axe',
    desc:
      'During your melee attack targeting a Living Corpse, Living Spirit, or Living Bones, add +5 (Symbol:Attack) to a single attack.',
    count: 1,
    gold: 50,
    effects: '',
    when: {
      type: WHEN.MELEE_ATTACK_TARGETING_ENEMY,
      enemies: [ENEMY.LIVING_CORPSE, ENEMY.LIVING_SPIRIT, ENEMY.LIVING_BONES],
    },
    what: [{ type: WHAT.ADD_X_ATTACK, count: 5 }],
    after: AFTER.SPENT,
    slot: SLOT.TWO_HANDS,
    type: TYPE.OTHER,
  },
  [ID.STAFF_OF_XORN]: {
    id: ID.STAFF_OF_XORN,
    name: 'Staff of Xorn',
    desc: 'During your ranged attack, add (Effect:Poison) and (Effect:Muddle) to the entire Attack action',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.ENTIRE_RANGED_ATTACK_ACTION },
    what: [{ type: WHAT.POISON }, { type: WHAT.MUDDLE }],
    after: AFTER.CONSUMED,
    slot: SLOT.TWO_HANDS,
    type: TYPE.OTHER,
  },
  [ID.MOUNTAIN_HAMMER]: {
    id: ID.MOUNTAIN_HAMMER,
    name: 'Mountain Hammer',
    desc: 'Summon (summon:WarriorSpirit)',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.SUMMON, summon: SUMMON.WARRIOR_SPIRIT }],
    after: AFTER.CONSUMED,
    slot: SLOT.TWO_HANDS,
    type: TYPE.OTHER,
  },
  [ID.FUELED_FALCHION]: {
    id: ID.FUELED_FALCHION,
    name: 'Fueled Falchion',
    desc: 'During your single-target melee attack, the target and all enemies adjacent to the target suffer 1 damage',
    count: 1,
    gold: 20,
    effects: '',
    when: { type: WHEN.SINGLE_TARGET_MELEE_ATTACK },
    what: [{ type: WHAT.TARGET_AND_ALL_ADJACENT_ENEMIES_SUFFER_DAMAGE, count: 1 }],
    after: AFTER.CONSUMED,
    slot: SLOT.ONE_HAND,
    type: TYPE.OTHER,
  },
  [ID.BLOODY_AXE]: {
    id: ID.BLOODY_AXE,
    name: 'Bloody Axe',
    desc: 'During your melee attack, suffer 2 damage to add +1 (Symbol:Attack) to the entire Attack action.',
    count: 1,
    gold: 40,
    effects: '',
    when: { type: WHEN.ENTIRE_MELEE_ATTACK_ACTION },
    what: [{ type: WHAT.SUFFER_DAMAGE, count: 2 }, { type: WHAT.ADD_X_ATTACK, count: 1 }],
    after: AFTER.SPENT,
    slot: SLOT.ONE_HAND,
    type: TYPE.OTHER,
  },
  [ID.STAFF_OF_ELEMENTS]: {
    id: ID.STAFF_OF_ELEMENTS,
    name: 'Staff of Elements',
    desc: 'During your turn, create (Element:Any).',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.CREATE_ANY_ELEMENT }],
    after: AFTER.SPENT,
    slot: SLOT.TWO_HANDS,
    type: TYPE.OTHER,
  },
  [ID.SKULL_OF_HATRED]: {
    id: ID.SKULL_OF_HATRED,
    name: 'Skull of Hatred',
    desc: 'During your turn, (Effect:Curse) all adjacent enemies.',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.CURSE_ADJACENT_ENEMIES }],
    after: AFTER.CONSUMED,
    slot: SLOT.ONE_HAND,
    type: TYPE.OTHER,
  },
  [ID.STAFF_OF_SUMMONING]: {
    id: ID.STAFF_OF_SUMMONING,
    name: 'Staff of Summoning',
    desc:
      'During your turn, a summoned ally within (Symbol:Range) 3 performs a "(Symbol:Move) 3" action with you controlling the action.',
    count: 1,
    gold: 60,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.MOVE_SUMMON, move: 3 }],
    after: AFTER.SPENT,
    slot: SLOT.TWO_HANDS,
    type: TYPE.OTHER,
  },
  [ID.ORB_OF_DAWN]: {
    id: ID.ORB_OF_DAWN,
    name: 'Orb of Dawn',
    desc: 'During your turn, (Element:Dark:Consume) to create (Element:Light).',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.TURN },
    what: [
      { type: WHAT.CONSUME_ELEMENT, element: ELEMENT.DARK },
      { type: WHAT.CREATE_ELEMENT, element: ELEMENT.LIGHT },
    ],
    after: AFTER.NONE,
    slot: SLOT.ONE_HAND,
    type: TYPE.OTHER,
  },
  [ID.ORB_OF_TWILIGHT]: {
    id: ID.ORB_OF_TWILIGHT,
    name: 'Orb of Twilight',
    desc: 'During your turn, (Element:Light:Consume) to create (Element:Dark).',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.TURN },
    what: [
      { type: WHAT.CONSUME_ELEMENT, element: ELEMENT.LIGHT },
      { type: WHAT.CREATE_ELEMENT, element: ELEMENT.DARK },
    ],
    after: AFTER.NONE,
    slot: SLOT.ONE_HAND,
    type: TYPE.OTHER,
  },
  [ID.RING_OF_SKULLS]: {
    id: ID.RING_OF_SKULLS,
    name: 'Ring of Skulls',
    desc: 'Summon (summon:Skeleton)',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.SUMMON, summon: SUMMON.SKELETON }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.OTHER,
  },
  [ID.DOOMED_COMPASS]: {
    id: ID.DOOMED_COMPASS,
    name: 'Doomed Compass',
    desc:
      'During your turn, force an enemy within (Symbol:Range) 5 to perform a "(Symbol:Move) 2" action with you controlling the action.',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.MOVE_ENEMEY, range: 5, count: 2 }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.OTHER,
  },
  [ID.CURIOUS_GEAR]: {
    id: ID.CURIOUS_GEAR,
    name: 'Curious Gear',
    desc: 'During your turn, disarm all traps within (Symbol:Range) 2.',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.DISARM_TRAPS, range: 2 }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.OTHER,
  },
  [ID.REMOTE_SPIDER]: {
    id: ID.REMOTE_SPIDER,
    name: 'Remote Spider',
    desc: 'During your turn, (Effect:Poison) all adjacent enemies.',
    count: 1,
    gold: 40,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.POISON_ADJACENT_ENEMIES }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.OTHER,
  },
  [ID.GIANT_REMOTE_SPIDER]: {
    id: ID.GIANT_REMOTE_SPIDER,
    name: 'Giant Remote Spider',
    desc: 'During your turn, perform a "(Symbol:Loot) 1" action.',
    count: 1,
    gold: 60,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.LOOT, range: 1 }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.OTHER,
  },
  [ID.BLACK_CENSER]: {
    id: ID.BLACK_CENSER,
    name: 'Black Censer',
    desc: 'During your turn, (Effect:Muddle) all enemies with (Symbol:Range) 2.',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.MUDDLE_ENEMIES, range: 2 }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.OTHER,
  },
  [ID.BLACK_CARD]: {
    id: ID.BLACK_CARD,
    name: 'Black Card',
    desc:
      'During your turn, place a character token on an adjacent normal or elite enemy. You add +1 (Symbol:Attack) to all your attacks targeting this enemy.',
    count: 1,
    gold: 75,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.PLACE_CHARACTER_TOKEN_ON_ENEMY, note: 'Add +1 attack to all your attacks on this enemy.' }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.OTHER,
  },
  [ID.HELIX_RING]: {
    id: ID.HELIX_RING,
    name: 'Helix Ring',
    desc:
      'During your turn, (Element:Light:Consume) and (Element:Dark:Consume) to perform a "(Symbol:Heal) 25, Self" action',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.TURN },
    what: [
      { type: WHAT.CONSUME_ELEMENT, element: ELEMENT.LIGHT },
      { type: WHAT.CONSUME_ELEMENT, element: ELEMENT.DARK },
      { type: WHAT.HEAL, count: 25 },
    ],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.OTHER,
  },
  [ID.HEART_OF_THE_BETRAYER]: {
    id: ID.HEART_OF_THE_BETRAYER,
    name: 'Heart of the Betrayer',
    desc:
      'When attacked by an adjacent normal enemy, force the enemy to attack one of its allies within its range instead',
    count: 1,
    gold: 60,
    effects: '',
    when: { type: WHEN.ATTACKED_BY_ADJACENT_NORMAL_ENEMY },
    what: [{ type: WHAT.ATTACKER_ATTACKS_ITS_ALLY_WITHIN_RANGE }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.OTHER,
  },
  [ID.POWER_CORE]: {
    id: ID.POWER_CORE,
    name: 'Power Core',
    desc: 'Summon (summon:SteelConstruct)',
    count: 1,
    gold: 75,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.SUMMON, summon: SUMMON.STEEL_CONSTRUCT }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.OTHER,
  },
  [ID.RESONANT_CRYSTAL]: {
    id: ID.RESONANT_CRYSTAL,
    name: 'Resonant Crystal',
    desc: 'During your turn, destroy an adjacent obstacle.',
    count: 1,
    gold: 20,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.DESTROY_ADJACENT_OBSTACLES }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.OTHER,
  },
  [ID.IMPOSING_BLADE]: {
    id: ID.IMPOSING_BLADE,
    name: 'Imposing Blade',
    desc: 'Any time you kill an enemy during your turn, gain (Symbol:Shield) 1 for the rest of the round.',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.KILL_ENEMY },
    what: [{ type: WHAT.SHIELD, count: 1 }],
    after: AFTER.NONE,
    slot: SLOT.ONE_HAND,
    type: TYPE.SOLO_SCENARIO,
  },
  [ID.FOCUSING_RAY]: {
    id: ID.FOCUSING_RAY,
    name: 'Focusing Ray',
    desc: 'During your Heal action, double the value of the Heal.',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.HEAL },
    what: [{ type: WHAT.HEAL_DOUBLE }],
    after: AFTER.CONSUMED,
    slot: SLOT.ONE_HAND,
    type: TYPE.SOLO_SCENARIO,
  },
  [ID.VOLATILE_ELIXIR]: {
    id: ID.VOLATILE_ELIXIR,
    name: 'Volatile Elixir',
    desc:
      'During your ranged attack, add +2 (Symbol:Attack) and gain Advantage on the entire Attack action, but suffer 2 damage for each attack made.',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.ENTIRE_RANGED_ATTACK_ACTION },
    what: [
      { type: WHAT.ADD_X_ATTACK, count: 2 },
      { type: WHAT.ADVANTAGE },
      { type: WHAT.SUFFER_DAMAGE, count: 2, note: 'Per attack.' },
    ],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.SOLO_SCENARIO,
  },
  [ID.SILENT_STILETTO]: {
    id: ID.SILENT_STILETTO,
    name: 'Silent Stiletto',
    desc: 'Any time you perform a melee attack, add (Effect:Pierce) 1 to the Attack.',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.ENTIRE_MELEE_ATTACK_ACTION },
    what: [{ type: WHAT.ADD_X_PIERCE, count: 1 }],
    after: AFTER.NONE,
    slot: SLOT.ONE_HAND,
    type: TYPE.SOLO_SCENARIO,
  },
  [ID.STONE_CHARM]: {
    id: ID.STONE_CHARM,
    name: 'Stone Charm',
    desc:
      'During your action where an obstacle is created, create one additional obstacle and apply all effects of the action to it.',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.CREATED_OBSTACLE },
    what: [{ type: WHAT.CREATE_OBSTACLE, note: 'Apply all effects of the action to it.' }],
    after: AFTER.SPENT,
    slot: SLOT.HEAD,
    type: TYPE.SOLO_SCENARIO,
  },
  [ID.PSYCHIC_KNIFE]: {
    id: ID.PSYCHIC_KNIFE,
    name: 'Psychic Knife',
    desc: 'Any time you perform an Augment action, add +1 (Symbol:Attack) to the entire action.',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.AUGMENT },
    what: [{ type: WHAT.ADD_X_ATTACK, count: 1, note: 'Entire attack action' }],
    after: AFTER.NONE,
    slot: SLOT.ONE_HAND,
    type: TYPE.SOLO_SCENARIO,
  },
  [ID.SUN_SHIELD]: {
    id: ID.SUN_SHIELD,
    name: 'Sun Shield',
    desc: 'When damaged by an attack, you may (Element:Light:Consume) to gain (Symbol:Shield) 3 for the attack.',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.DAMAGED_BY_ATTACK },
    what: [{ type: WHAT.CONSUME_ELEMENT, element: ELEMENT.LIGHT }, { type: WHAT.SHIELD, count: 3 }],
    after: AFTER.NONE,
    slot: SLOT.ONE_HAND,
    type: TYPE.SOLO_SCENARIO,
  },
  [ID.UTILITY_BELT]: {
    id: ID.UTILITY_BELT,
    name: 'Utility Belt',
    desc: 'During your turn, you or any one ally may (Symbol:ItemRefresh) one of your spent or consumed items.',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.YOU_OR_ALLY_REFRESH_1_SPENT_OR_CONSUMED_ITEM }],
    after: AFTER.CONSUMED,
    slot: SLOT.NONE,
    type: TYPE.SOLO_SCENARIO,
  },
  [ID.PHASING_IDOL]: {
    id: ID.PHASING_IDOL,
    name: 'Phasing Idol',
    desc: 'When a summon you own is damaged by an attack, it suffers no damage instead.',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.SUMMON_DAMAGED },
    what: [{ type: WHAT.SUFFER_NO_DAMAGE }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.SOLO_SCENARIO,
  },
  [ID.SMOKE_ELIXIR]: {
    id: ID.SMOKE_ELIXIR,
    name: 'Smoke Elixir',
    desc: 'During your turn, gain (Effect:Invisible) and create (Element:Dark).',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.INVISIBLE }, { type: WHAT.CREATE_ELEMENT, element: ELEMENT.DARK }],
    after: AFTER.CONSUMED,
    slot: SLOT.SMALL_ITEM,
    type: TYPE.SOLO_SCENARIO,
  },
  [ID.PENDANT_OF_THE_PLAGUE]: {
    id: ID.PENDANT_OF_THE_PLAGUE,
    name: 'Pendant of the Plague',
    desc: 'During your turn, (Effect:Poison) and (Effect:Curse) one enemy within (Symbol:Range) 3.',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.TURN },
    what: [{ type: WHAT.POISON, range: 3 }, { type: WHAT.CURSE, range: 3 }],
    after: AFTER.SPENT,
    slot: SLOT.HEAD,
    type: TYPE.SOLO_SCENARIO,
  },
  [ID.MASK_OF_DEATH]: {
    id: ID.MASK_OF_DEATH,
    name: 'Mask of Death',
    desc: 'Any time you perform a melee attack and you have exactly 1 hit point, add +2 (Symbol:Attack) to the Attack.',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.MELEE_ATTACK_WITH_1_HP },
    what: [{ type: WHAT.ADD_X_ATTACK, count: 2 }],
    after: AFTER.NONE,
    slot: SLOT.HEAD,
    type: TYPE.SOLO_SCENARIO,
  },
  [ID.MASTERS_LUTE]: {
    id: ID.MASTERS_LUTE,
    name: 'Master’s Lute',
    desc: 'After performing any song action, immediately perform an (Attack:+2) or (Symbol:Move) 2 action.',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.SONG },
    what: [{ type: WHAT.ATTACK_OR_MOVE, count: 2 }],
    after: AFTER.NONE,
    slot: SLOT.TWO_HANDS,
    type: TYPE.SOLO_SCENARIO,
  },
  [ID.CLOAK_OF_THE_HUNTER]: {
    id: ID.CLOAK_OF_THE_HUNTER,
    name: 'Cloak of the Hunter',
    desc: 'Any time you perform a Doom action, (Effect:Muddle) the target of the Doom.',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.DOOM },
    what: [{ type: WHAT.MUDDLE }],
    after: AFTER.NONE,
    slot: SLOT.BODY,
    type: TYPE.SOLO_SCENARIO,
  },
  [ID.DOCTORS_COAT]: {
    id: ID.DOCTORS_COAT,
    name: 'Doctor’s Coat',
    desc:
      'Any time an ally performs a Medical Pack or Large Medical Pack action, they add +1 (Symbol:Heal) to their Heal.',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.ALLY_PERFORMS_MED_PACK },
    what: [{ type: WHAT.ADD_X_HEAL, count: 1 }],
    after: AFTER.NONE,
    slot: SLOT.BODY,
    type: TYPE.SOLO_SCENARIO,
  },
  [ID.ELEMENTAL_BOOTS]: {
    id: ID.ELEMENTAL_BOOTS,
    name: 'Elemental Boots',
    desc: 'If you move 5 or more hexes on your turn, create (Element:Any).',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.MOVE_X_OR_MORE, count: 5 },
    what: [{ type: WHAT.CREATE_ANY_ELEMENT }],
    after: AFTER.SPENT,
    slot: SLOT.LEGS,
    type: TYPE.SOLO_SCENARIO,
  },
  [ID.STAFF_OF_COMMAND]: {
    id: ID.STAFF_OF_COMMAND,
    name: 'Staff of Command',
    desc:
      'After performing a Command action, play one card from your hand and immediately perform the same side of the card (top or bottom) as the Command action.',
    count: 1,
    gold: 50,
    effects: '',
    when: { type: WHEN.COMMAND },
    what: [{ type: WHAT.PLAY_CARD_FROM_HAND, note: 'Perform the same side (top or bottom) as the Command action.' }],
    after: AFTER.SPENT,
    slot: SLOT.TWO_HANDS,
    type: TYPE.SOLO_SCENARIO,
  },
};
