import ID from './ID';

export default {
  [ID.ANCIENT_TECHNOLOGY]: { id: ID.ANCIENT_TECHNOLOGY, name: 'Ancient Technology' },
  [ID.ANNIHILATION_OF_ORDER]: { id: ID.ANNIHILATION_OF_ORDER, name: 'Annihilation of Order' },
  [ID.ARTIFACT_CLEANSED]: { id: ID.ARTIFACT_CLEANSED, name: 'Artifact Cleansed' },
  [ID.ARTIFACT_LOST]: { id: ID.ARTIFACT_LOST, name: 'Artifact Lost' },
  [ID.ARTIFACT_RECOVERED]: { id: ID.ARTIFACT_RECOVERED, name: 'Artifact Recovered' },
  [ID.CITY_RULE_DEMONIC]: { id: ID.CITY_RULE_DEMONIC, name: 'City Rule: Demonic' },
  [ID.CITY_RULE_ECONOMIC]: { id: ID.CITY_RULE_ECONOMIC, name: 'City Rule: Economic' },
  [ID.CITY_RULE_MILITARISTIC]: { id: ID.CITY_RULE_MILITARISTIC, name: 'City Rule: Militaristic' },
  [ID.END_OF_CORRUPTION]: { id: ID.END_OF_CORRUPTION, name: 'End of Corruption' },
  [ID.END_OF_GLOOM]: { id: ID.END_OF_GLOOM, name: 'End of Gloom' },
  [ID.END_OF_THE_INVASION]: { id: ID.END_OF_THE_INVASION, name: 'End of the Invasion' },
  [ID.THE_DEAD_INVADE]: { id: ID.THE_DEAD_INVADE, name: 'The Dead Invade' },
  [ID.THE_DRAKE_AIDED]: { id: ID.THE_DRAKE_AIDED, name: 'The Drake Aided' },
  [ID.THE_EDGE_OF_DARKNESS]: { id: ID.THE_EDGE_OF_DARKNESS, name: 'The Edge of Darkness' },
  [ID.THE_MERCHANT_FLEES]: { id: ID.THE_MERCHANT_FLEES, name: 'The Merchant Flees' },
  [ID.THE_POWER_OF_ENHANCEMENT]: { id: ID.THE_POWER_OF_ENHANCEMENT, name: 'The Power of Enhancement' },
  [ID.THE_RIFT_NEUTRALIZED]: { id: ID.THE_RIFT_NEUTRALIZED, name: 'The Rift Neutralized' },
  [ID.THE_VOICE_FREED]: { id: ID.THE_VOICE_FREED, name: 'The Voice Freed' },
  [ID.THE_VOICE_SILENCED]: { id: ID.THE_VOICE_SILENCED, name: 'The Voice Silenced' },
  [ID.WATER_BREATHING]: { id: ID.WATER_BREATHING, name: 'Water Breathing' },
  [ID.THE_DRAKE_SLAIN]: { id: ID.THE_DRAKE_SLAIN, name: 'The Drake Slain' },
};
