import { ENEMY, PERSONAL_QUEST } from '../../../constants';

export default quest => {
  switch (quest) {
    case PERSONAL_QUEST.ABERRANT_SLAYER:
      return [
        ENEMY.EARTH_DEMON,
        ENEMY.FLAME_DEMON,
        ENEMY.FROST_DEMON,
        ENEMY.NIGHT_DEMON,
        ENEMY.SUN_DEMON,
        ENEMY.WIND_DEMON,
      ];
    case PERSONAL_QUEST.FINDING_THE_CURE:
      return [ENEMY.FOREST_IMP];
    case PERSONAL_QUEST.LAWBRINGER:
      return [ENEMY.BANDIT_ARCHER, ENEMY.BANDIT_GUARD, ENEMY.BANDIT_COMMANDER, ENEMY.CULTIST];
    case PERSONAL_QUEST.POUNDS_OF_FLESH:
      return [ENEMY.VERMLING_SCOUT, ENEMY.VERMLING_SHAMAN];
    case PERSONAL_QUEST.TROPHY_HUNT:
    case PERSONAL_QUEST.FEARLESS_STAND:
      return Object.values(ENEMY);
    case PERSONAL_QUEST.IMPLEMENT_OF_LIGHT:
      return [ENEMY.LIVING_BONES, ENEMY.LIVING_CORPSE, ENEMY.LIVING_SPIRIT];
    case PERSONAL_QUEST.THE_PERFECT_POISON:
      return [ENEMY.OOZE, ENEMY.LURKER, ENEMY.SPITTING_DRAKE];
    default:
      return [];
  }
};
