import ID from './ID';

export default {
  [ID.AVAILABLE]: {
    id: ID.AVAILABLE,
    name: 'Available',
    text: 'Available',
    enabled: () => false,
    cost: 0,
  },
  [ID.PLUS1]: {
    id: ID.PLUS1,
    name: '+1',
    text: '(Symbol:Plus1)',
    enabled: aug => aug.numeric,
    cost: 0,
  },
  [ID.EFFECT_POISON]: {
    id: ID.EFFECT_POISON,
    name: 'Poison',
    text: '(Effect:Poison)',
    enabled: aug => aug.main && aug.enemy,
    cost: 75,
  },
  [ID.EFFECT_WOUND]: {
    id: ID.EFFECT_WOUND,
    name: 'Wound',
    text: '(Effect:Wound)',
    enabled: aug => aug.main && aug.enemy,
    cost: 75,
  },
  [ID.EFFECT_MUDDLE]: {
    id: ID.EFFECT_MUDDLE,
    name: 'Muddle',
    text: '(Effect:Muddle)',
    enabled: aug => aug.main && aug.enemy,
    cost: 50,
  },
  [ID.EFFECT_IMMOBILIZE]: {
    id: ID.EFFECT_IMMOBILIZE,
    name: 'Immobilize',
    text: '(Effect:Immobilize)',
    enabled: aug => aug.main && aug.enemy,
    cost: 100,
  },
  [ID.EFFECT_DISARM]: {
    id: ID.EFFECT_DISARM,
    name: 'Disarm',
    text: '(Effect:Disarm)',
    enabled: aug => aug.main && aug.enemy,
    cost: 150,
  },
  [ID.EFFECT_CURSE]: {
    id: ID.EFFECT_CURSE,
    name: 'Curse',
    text: '(Effect:Curse)',
    enabled: aug => aug.main && aug.enemy,
    cost: 75,
  },
  [ID.EFFECT_STRENGTHEN]: {
    id: ID.EFFECT_STRENGTHEN,
    name: 'Strengthen',
    text: '(Effect:Strengthen)',
    enabled: aug => aug.main && aug.self,
    cost: 50,
  },
  [ID.EFFECT_BLESS]: {
    id: ID.EFFECT_BLESS,
    name: 'Bless',
    text: '(Effect:Bless)',
    enabled: aug => aug.main && aug.self,
    cost: 50,
  },
  [ID.JUMP]: {
    id: ID.JUMP,
    name: 'Jump',
    text: '(Symbol:Jump)',
    enabled: aug => aug.move,
    cost: 50,
  },
  [ID.ELEMENT_AIR]: {
    id: ID.ELEMENT_AIR,
    name: 'Air',
    text: '(Element:Air)',
    enabled: aug => aug.main,
    cost: 100,
  },
  [ID.ELEMENT_ICE]: {
    id: ID.ELEMENT_ICE,
    name: 'Ice',
    text: '(Element:Ice)',
    enabled: aug => aug.main,
    cost: 100,
  },
  [ID.ELEMENT_FIRE]: {
    id: ID.ELEMENT_FIRE,
    name: 'Fire',
    text: '(Element:Fire)',
    enabled: aug => aug.main,
    cost: 100,
  },
  [ID.ELEMENT_LIGHT]: {
    id: ID.ELEMENT_LIGHT,
    name: 'Light',
    text: '(Element:Light)',
    enabled: aug => aug.main,
    cost: 100,
  },
  [ID.ELEMENT_DARK]: {
    id: ID.ELEMENT_DARK,
    name: 'Dark',
    text: '(Element:Dark)',
    enabled: aug => aug.main,
    cost: 100,
  },
  [ID.ELEMENT_EARTH]: {
    id: ID.ELEMENT_EARTH,
    name: 'Earth',
    text: '(Element:Earth)',
    enabled: aug => aug.main,
    cost: 100,
  },
  [ID.ELEMENT_ANY]: {
    id: ID.ELEMENT_ANY,
    name: 'Any',
    text: '(Element:Any)',
    enabled: aug => aug.main,
    cost: 150,
  },
  [ID.HEX]: {
    id: ID.HEX,
    name: 'Hex',
    text: '(Hex:Pattern:R)',
    enabled: aug => aug.hex,
    cost: 0,
  },
};
