export default {
  UNKNOWN: '??',
  GLOOMHAVEN: 'GH',
  DAGGER_FOREST: 'DF',
  LINGERING_SWAMP: 'LS',
  WATCHER_MOUNTAINS: 'WM',
  COPPERNECK_MOUNTAINS: 'CM',
  MISTY_SEA: 'MS',
  CRYPT: 'CR',
};
