import { ATTACK_MODIFIER_CARD } from '../ATTACK_MODIFIER_CARD';
import { CLASS } from '../CLASS';
import { ENEMY } from '../ENEMY';
import { ENVELOPE } from '../ENVELOPE';
import { GLOBAL_ACHIEVEMENT } from '../GLOBAL_ACHIEVEMENT';
import { ITEM } from '../ITEM';
import { PARTY_ACHIEVEMENT } from '../PARTY_ACHIEVEMENT';
import { PERSONAL_QUEST } from '../PERSONAL_QUEST';
import { REGION } from '../REGION';
import { SCENARIO_REQUIREMENT } from '../SCENARIO_REQUIREMENT';
import ID from './ID';
import EFFECT from './EFFECT_TYPE';
import GOAL from './GOAL_TYPE';
import REWARD from './REWARD_TYPE';

export default {
  [ID.BLACK_BARROW]: {
    id: ID.BLACK_BARROW,
    name: 'Black Barrow',
    region: REGION.UNKNOWN,
    links: [ID.BARROW_LAIR],
    requirements: [],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }],
    effects: [],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.BARROW_LAIR },
      { type: REWARD.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.FIRST_STEPS },
    ],
  },
  [ID.BARROW_LAIR]: {
    id: ID.BARROW_LAIR,
    name: 'Barrow Lair',
    region: REGION.UNKNOWN,
    links: [ID.BLACK_BARROW],
    boss: true,
    requirements: [
      { type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.FIRST_STEPS, complete: true },
    ],
    goals: [{ type: GOAL.KILL_ENEMY, enemy: ENEMY.BANDIT_COMMANDER }, { type: GOAL.KILL_ALL_REVEALED_ENEMIES }],
    effects: [{ type: EFFECT.ADD_X_CARDS, count: 3, card: ATTACK_MODIFIER_CARD.CURSE }],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.INOX_ENCAPMENT },
      { type: REWARD.SCENARIO, scenario: ID.CRYPT_OF_THE_DAMNED },
      { type: REWARD.GOLD, count: 10 },
      { type: REWARD.PROSPERITY, count: 1 },
    ],
  },
  [ID.INOX_ENCAPMENT]: {
    id: ID.INOX_ENCAPMENT,
    name: 'Inox Encapment',
    region: REGION.DAGGER_FOREST,
    links: [],
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
        achievement: GLOBAL_ACHIEVEMENT.THE_MERCHANT_FLEES,
        complete: false,
      },
    ],
    goals: [{ type: GOAL.KILL_X_TIMES_CHARACTERS_ENEMIES, count: 5 }],
    effects: [],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.GLOOMHAVEN_WAREHOUSE },
      { type: REWARD.SCENARIO, scenario: ID.DIAMOND_MINE },
      { type: REWARD.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.JEKSERAHS_PLANS },
      { type: REWARD.GOLD, count: 15 },
      { type: REWARD.PROSPERITY, count: 1 },
    ],
  },
  [ID.CRYPT_OF_THE_DAMNED]: {
    id: ID.CRYPT_OF_THE_DAMNED,
    name: 'Crypt of the Damned',
    region: REGION.UNKNOWN,
    crypt: true,
    links: [],
    requirements: [],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }],
    effects: [],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.RUINOUS_CRYPT },
      { type: REWARD.SCENARIO, scenario: ID.DECAYING_CRYPT },
    ],
  },
  [ID.RUINOUS_CRYPT]: {
    id: ID.RUINOUS_CRYPT,
    name: 'Ruinous Crypt',
    region: REGION.UNKNOWN,
    crypt: true,
    links: [ID.PLANE_OF_ELEMENTAL_POWER],
    requirements: [],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }],
    effects: [{ type: EFFECT.DISARM }],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.PLANE_OF_ELEMENTAL_POWER },
      { type: REWARD.SCENARIO, scenario: ID.FROZEN_HOLLOW },
      { type: REWARD.SCENARIO, scenario: ID.FORGOTTEN_CRYPT },
    ],
  },
  [ID.DECAYING_CRYPT]: {
    id: ID.DECAYING_CRYPT,
    name: 'Decaying Crypt',
    region: REGION.UNKNOWN,
    crypt: true,
    links: [],
    requirements: [],
    goals: [{ type: GOAL.REVEAL }, { type: GOAL.KILL_ALL_REVEALED_ENEMIES }],
    effects: [{ type: EFFECT.ADD_X_CARDS, count: 3, card: ATTACK_MODIFIER_CARD.CURSE }],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.GLOOMHAVEN_WAREHOUSE },
      { type: REWARD.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.JEKSERAHS_PLANS },
      { type: REWARD.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.DARK_BOUNTY },
      { type: REWARD.GOLD, count: 5 },
    ],
  },
  [ID.VIBRANT_GROTTO]: {
    id: ID.VIBRANT_GROTTO,
    name: 'Vibrant Grotto',
    region: REGION.COPPERNECK_MOUNTAINS,
    links: [],
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
        achievement: GLOBAL_ACHIEVEMENT.THE_POWER_OF_ENHANCEMENT,
        complete: true,
      },
      {
        type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
        achievement: GLOBAL_ACHIEVEMENT.THE_MERCHANT_FLEES,
        complete: true,
      },
    ],
    goals: [{ type: GOAL.LOOT_ALL_TREASURE_TILES }],
    effects: [],
    rewards: [{ type: REWARD.SCENARIO, scenario: ID.NECROMANCERS_SANCTUM }],
  },
  [ID.GLOOMHAVEN_WAREHOUSE]: {
    id: ID.GLOOMHAVEN_WAREHOUSE,
    name: 'Gloomhaven Warehouse',
    boss: true,
    region: REGION.GLOOMHAVEN,
    links: gloomhavenLinks(ID.GLOOMHAVEN_WAREHOUSE),
    linksGloomhaven: true,
    requirements: [
      { type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.JEKSERAHS_PLANS, complete: true },
      {
        type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
        achievement: GLOBAL_ACHIEVEMENT.THE_DEAD_INVADE,
        complete: false,
      },
    ],
    goals: [{ type: GOAL.KILL_X_ENEMIES, count: 2, enemies: [ENEMY.INOX_BODYGUARD] }],
    effects: [],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.VIBRANT_GROTTO },
      { type: REWARD.SCENARIO, scenario: ID.TEMPLE_OF_THE_SEER },
      { type: REWARD.SCENARIO, scenario: ID.FROZEN_HOLLOW },
      { type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.THE_MERCHANT_FLEES },
      { type: REWARD.REPUTATION, count: 2 },
    ],
  },
  [ID.DIAMOND_MINE]: {
    id: ID.DIAMOND_MINE,
    name: 'Diamond Mine',
    boss: true,
    region: REGION.WATCHER_MOUNTAINS,
    links: [],
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
        achievement: GLOBAL_ACHIEVEMENT.THE_MERCHANT_FLEES,
        complete: false,
      },
    ],
    goals: [{ type: GOAL.KILL_ENEMY, enemy: ENEMY.MERCILESS_OVERSEER }, { type: GOAL.LOOT_ALL_TREASURE_TILES }],
    effects: [],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.GLOOMHAVEN_SQUARE_A },
      { type: REWARD.SCENARIO, scenario: ID.GLOOMHAVEN_SQUARE_B },
      { type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.THE_DEAD_INVADE },
      { type: REWARD.GOLD, count: 20 },
      { type: REWARD.PROSPERITY, count: 1 },
    ],
  },
  [ID.PLANE_OF_ELEMENTAL_POWER]: {
    id: ID.PLANE_OF_ELEMENTAL_POWER,
    name: 'Plane of Elemental Power',
    region: REGION.UNKNOWN,
    links: [ID.RUINOUS_CRYPT, ID.INFERNAL_THRONE],
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
        achievement: GLOBAL_ACHIEVEMENT.THE_RIFT_NEUTRALIZED,
        complete: false,
      },
    ],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }],
    effects: [],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.INFERNAL_THRONE },
      { type: REWARD.SCENARIO, scenario: ID.TEMPLE_OF_THE_ELEMENTS },
      { type: REWARD.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.A_DEMONS_ERRAND },
    ],
  },
  [ID.GLOOMHAVEN_SQUARE_A]: {
    id: ID.GLOOMHAVEN_SQUARE_A,
    name: 'Gloomhaven Square A',
    boss: true,
    region: REGION.GLOOMHAVEN,
    links: gloomhavenLinks(ID.GLOOMHAVEN_SQUARE_A),
    linksGloomhaven: true,
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
        achievement: GLOBAL_ACHIEVEMENT.END_OF_THE_INVASION,
        complete: false,
      },
    ],
    goals: [{ type: GOAL.KILL_ENEMY, enemy: ENEMY.CAPTAIN_OF_THE_GUARD }],
    effects: [],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.MOUNTAIN_PASS },
      { type: REWARD.SCENARIO, scenario: ID.ABANDONED_SEWERS },
      { type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.CITY_RULE_ECONOMIC },
      { type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.END_OF_THE_INVASION },
      { type: REWARD.GOLD, count: 15 },
      { type: REWARD.REPUTATION, count: -2 },
      { type: REWARD.PROSPERITY, count: 2 },
      { type: REWARD.ITEM_DESIGN, item: ITEM.SKULLBANE_AXE },
    ],
  },
  [ID.GLOOMHAVEN_SQUARE_B]: {
    id: ID.GLOOMHAVEN_SQUARE_B,
    name: 'Gloomhaven Square B',
    boss: true,
    region: REGION.GLOOMHAVEN,
    links: gloomhavenLinks(ID.GLOOMHAVEN_SQUARE_B),
    linksGloomhaven: true,
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
        achievement: GLOBAL_ACHIEVEMENT.END_OF_THE_INVASION,
        complete: false,
      },
    ],
    goals: [{ type: GOAL.KILL_ENEMY, enemy: ENEMY.JEKSERAH }],
    effects: [],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.MOUNTAIN_PASS },
      { type: REWARD.SCENARIO, scenario: ID.ABANDONED_SEWERS },
      { type: REWARD.SCENARIO, scenario: ID.OUTER_RITUAL_CHAMBER },
      { type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.END_OF_THE_INVASION },
      { type: REWARD.REPUTATION, count: 4 },
      { type: REWARD.ITEM_DESIGN, item: ITEM.SKULLBANE_AXE },
    ],
  },
  [ID.TEMPLE_OF_THE_SEER]: {
    id: ID.TEMPLE_OF_THE_SEER,
    name: 'Temple of the Seer',
    region: REGION.WATCHER_MOUNTAINS,
    links: [],
    requirements: [],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }],
    effects: [],
    rewards: [
      { type: REWARD.CHOOSE_1_SCENARIO, scenarios: [ID.SHRINE_OF_STRENGTH, ID.LOST_ISLAND, ID.NECROMANCERS_SANCTUM] },
    ],
  },
  [ID.FROZEN_HOLLOW]: {
    id: ID.FROZEN_HOLLOW,
    name: 'Frozen Hollow',
    region: REGION.COPPERNECK_MOUNTAINS,
    links: [],
    requirements: [],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }],
    effects: [{ type: EFFECT.ADD_X_CARDS, count: 3, card: ATTACK_MODIFIER_CARD.NEG_1 }],
    rewards: [{ type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.THE_POWER_OF_ENHANCEMENT }],
  },
  [ID.SHRINE_OF_STRENGTH]: {
    id: ID.SHRINE_OF_STRENGTH,
    name: 'Shrine of Strength',
    region: REGION.COPPERNECK_MOUNTAINS,
    links: [],
    requirements: [],
    goals: [{ type: GOAL.LOOT_ALL_TREASURE_TILES }],
    effects: [],
    rewards: [{ type: REWARD.XP, count: 20 }],
  },
  [ID.MOUNTAIN_PASS]: {
    id: ID.MOUNTAIN_PASS,
    name: 'Mountain Pass',
    region: REGION.COPPERNECK_MOUNTAINS,
    links: [ID.ECHO_CHAMBER],
    requirements: [],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }],
    effects: [],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.ECHO_CHAMBER },
      { type: REWARD.SCENARIO, scenario: ID.ICECRAG_ASCENT },
    ],
  },
  [ID.LOST_ISLAND]: {
    id: ID.LOST_ISLAND,
    name: 'Lost Island',
    region: REGION.MISTY_SEA,
    links: gloomhavenLinks(ID.LOST_ISLAND),
    linksGloomhaven: true,
    requirements: [],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }],
    effects: [],
    rewards: [{ type: REWARD.GOLD, count: 25 }],
  },
  [ID.ABANDONED_SEWERS]: {
    id: ID.ABANDONED_SEWERS,
    name: 'Abandoned Sewers',
    region: REGION.GLOOMHAVEN,
    links: gloomhavenLinks(ID.ABANDONED_SEWERS),
    linksGloomhaven: true,
    requirements: [],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }],
    effects: [],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.FROZEN_HOLLOW },
      { type: REWARD.SCENARIO, scenario: ID.DEEP_RUINS },
      { type: REWARD.SCENARIO, scenario: ID.ANCIENT_CISTERN },
      { type: REWARD.SCENARIO, scenario: ID.DRAKE_NEST },
    ],
  },
  [ID.FORGOTTEN_CRYPT]: {
    id: ID.FORGOTTEN_CRYPT,
    name: 'Forgotten Crypt',
    region: REGION.LINGERING_SWAMP,
    crypt: true,
    links: [],
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
        achievement: GLOBAL_ACHIEVEMENT.THE_POWER_OF_ENHANCEMENT,
        complete: true,
      },
    ],
    goals: [{ type: GOAL.PROTECT }],
    effects: [{ type: EFFECT.ADD_X_CARDS, count: 3, card: ATTACK_MODIFIER_CARD.CURSE }],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.RUINOUS_RIFT },
      { type: REWARD.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.STONEBREAKERS_CENSER },
      { type: REWARD.PROSPERITY, count: 1 },
    ],
  },
  [ID.NECROMANCERS_SANCTUM]: {
    id: ID.NECROMANCERS_SANCTUM,
    name: "Necromancer's Sanctum",
    boss: true,
    region: REGION.UNKNOWN,
    links: [],
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
        achievement: GLOBAL_ACHIEVEMENT.THE_MERCHANT_FLEES,
        complete: true,
      },
    ],
    goals: [{ type: GOAL.KILL_ENEMY, enemy: ENEMY.JEKSERAH }],
    effects: [],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.MOUNTAIN_PASS },
      { type: REWARD.SCENARIO, scenario: ID.ABANDONED_SEWERS },
      { type: REWARD.SCENARIO, scenario: ID.OUTER_RITUAL_CHAMBER },
      { type: REWARD.GOLD, count: 20 },
      { type: REWARD.REPUTATION, count: 2 },
      { type: REWARD.PROSPERITY, count: 1 },
    ],
  },
  [ID.INFERNAL_THRONE]: {
    id: ID.INFERNAL_THRONE,
    name: 'Infernal Throne',
    boss: true,
    region: REGION.UNKNOWN,
    links: [ID.PLANE_OF_ELEMENTAL_POWER],
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
        achievement: GLOBAL_ACHIEVEMENT.THE_RIFT_NEUTRALIZED,
        complete: false,
      },
    ],
    goals: [{ type: GOAL.KILL_ENEMY, enemy: ENEMY.PRIME_DEMON }],
    effects: [],
    rewards: [
      { type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.THE_RIFT_NEUTRALIZED },
      {
        type: REWARD.CONDITIONAL_GLOBAL_ACHIEVEMENT,
        condition: {
          type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
          achievement: GLOBAL_ACHIEVEMENT.ARTIFACT_LOST,
          complete: true,
        },
        achievement: GLOBAL_ACHIEVEMENT.ARTIFACT_RECOVERED,
      },
      { type: REWARD.GOLD, count: 50 },
      { type: REWARD.PROSPERITY, count: 1 },
      { type: REWARD.CITY_EVENT, event: 78 },
    ],
  },
  [ID.TEMPLE_OF_THE_ELEMENTS]: {
    id: ID.TEMPLE_OF_THE_ELEMENTS,
    name: 'Temple of the Elements',
    region: REGION.UNKNOWN,
    links: [],
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.ONE_OF,
        condition: [
          {
            type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT,
            achievement: PARTY_ACHIEVEMENT.A_DEMONS_ERRAND,
            complete: true,
          },
          {
            type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT,
            achievement: PARTY_ACHIEVEMENT.FOLLOWING_CLUES,
            complete: true,
          },
        ],
      },
    ],
    goals: [{ type: GOAL.DESTROY }],
    effects: [],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.PLANE_OF_NIGHT },
      { type: REWARD.SCENARIO, scenario: ID.GLOOMHAVEN_BATTLEMENTS_A },
      { type: REWARD.SCENARIO, scenario: ID.GLOOMHAVEN_BATTLEMENTS_B },
      { type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.ARTIFACT_RECOVERED },
    ],
  },
  [ID.DEEP_RUINS]: {
    id: ID.DEEP_RUINS,
    name: 'Deep Ruins',
    region: REGION.GLOOMHAVEN,
    links: gloomhavenLinks(ID.DEEP_RUINS),
    linksGloomhaven: true,
    requirements: [],
    goals: [{ type: GOAL.OCCUPY }],
    effects: [{ type: EFFECT.ADD_X_CARDS, count: 3, card: ATTACK_MODIFIER_CARD.NEG1 }],
    rewards: [
      { type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.ANCIENT_TECHNOLOGY },
      { type: REWARD.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.THROUGH_THE_RUINS },
    ],
  },
  [ID.ECHO_CHAMBER]: {
    id: ID.ECHO_CHAMBER,
    name: 'Echo Chamber',
    region: REGION.COPPERNECK_MOUNTAINS,
    links: [ID.MOUNTAIN_PASS],
    requirements: [],
    goals: [{ type: GOAL.OPEN }],
    effects: [],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.SHRINE_OF_THE_DEPTHS },
      { type: REWARD.SCENARIO, scenario: ID.DECREPIT_WOOD },
      { type: REWARD.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.THE_VOICES_COMMAND },
    ],
  },
  [ID.ICECRAG_ASCENT]: {
    id: ID.ICECRAG_ASCENT,
    name: 'Icecrag Ascent',
    region: REGION.COPPERNECK_MOUNTAINS,
    links: [ID.SCORCHED_SUMMIT],
    requirements: [],
    goals: [{ type: GOAL.EXIT }],
    effects: [{ type: EFFECT.ADD_X_CARDS, count: 2, card: ATTACK_MODIFIER_CARD.NEG1 }],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.SAVVAS_ARMORY },
      { type: REWARD.SCENARIO, scenario: ID.SCORCHED_SUMMIT },
      { type: REWARD.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.THE_DRAKES_COMMAND },
    ],
  },
  [ID.ANCIENT_CISTERN]: {
    id: ID.ANCIENT_CISTERN,
    name: 'Ancient Cistern',
    region: REGION.GLOOMHAVEN,
    links: gloomhavenLinks(ID.ANCIENT_CISTERN),
    linksGloomhaven: true,
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.ONE_OF,
        condition: [
          {
            type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
            achievement: GLOBAL_ACHIEVEMENT.WATER_BREATHING,
            complete: true,
          },
          {
            type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT,
            achievement: PARTY_ACHIEVEMENT.THROUGH_THE_RUINS,
            complete: true,
          },
        ],
      },
    ],
    goals: [{ type: GOAL.CLEANSE }],
    effects: [],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.TEMPLE_OF_THE_ELEMENTS },
      { type: REWARD.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.FOLLOWING_CLUES },
      { type: REWARD.GOLD, count: 10 },
      { type: REWARD.REPUTATION, count: 1 },
      { type: REWARD.PROSPERITY, count: 2 },
    ],
  },
  [ID.RUINOUS_RIFT]: {
    id: ID.RUINOUS_RIFT,
    name: 'Ruinous Rift',
    region: REGION.UNKNOWN,
    links: [],
    requirements: [
      { type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.ARTIFACT_LOST, complete: false },
      {
        type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT,
        achievement: PARTY_ACHIEVEMENT.STONEBREAKERS_CENSER,
        complete: true,
      },
    ],
    goals: [{ type: GOAL.PROTECT }],
    effects: [],
    rewards: [
      { type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.THE_RIFT_NEUTRALIZED },
      { type: REWARD.PROSPERITY, count: 1 },
      { type: REWARD.GOLD, count: 100, note: 'The money must immediately be spent on enhancements' },
    ],
  },
  [ID.OUTER_RITUAL_CHAMBER]: {
    id: ID.OUTER_RITUAL_CHAMBER,
    name: 'Outer Ritual Chamber',
    region: REGION.DAGGER_FOREST,
    links: [ID.SANCTUARY_OF_GLOOM],
    requirements: [
      { type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.DARK_BOUNTY, complete: true },
    ],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }],
    effects: [],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.SANCTUARY_OF_GLOOM },
      { type: REWARD.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.AN_INVITATION },
    ],
  },
  [ID.SANCTUARY_OF_GLOOM]: {
    id: ID.SANCTUARY_OF_GLOOM,
    name: 'Sanctuary of Gloom',
    region: REGION.DAGGER_FOREST,
    links: [ID.OUTER_RITUAL_CHAMBER],
    requirements: [
      { type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.AN_INVITATION, complete: true },
    ],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }],
    effects: [{ type: EFFECT.ADD_X_CARDS, count: 3, card: ATTACK_MODIFIER_CARD.NEG1 }],
    rewards: [
      { type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.THE_EDGE_OF_DARKNESS },
      { type: REWARD.XP, count: 15 },
    ],
  },
  [ID.SHRINE_OF_THE_DEPTHS]: {
    id: ID.SHRINE_OF_THE_DEPTHS,
    name: 'Shrine of the Depths',
    region: REGION.MISTY_SEA,
    links: [],
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT,
        achievement: PARTY_ACHIEVEMENT.THE_VOICES_COMMAND,
        complete: true,
      },
    ],
    goals: [{ type: GOAL.LOOT_ALL_TREASURE_TILES }],
    effects: [],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.REALM_OF_THE_VOICE },
      { type: REWARD.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.THE_SCEPTER_AND_THE_VOICE },
      { type: REWARD.GOLD, count: 10 },
    ],
  },
  [ID.PLANE_OF_NIGHT]: {
    id: ID.PLANE_OF_NIGHT,
    name: 'Plane of Night',
    region: REGION.GLOOMHAVEN,
    links: gloomhavenLinks(ID.PLANE_OF_NIGHT),
    linksGloomhaven: true,
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
        achievement: GLOBAL_ACHIEVEMENT.THE_POWER_OF_ENHANCEMENT,
        complete: true,
      },
      {
        type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
        achievement: GLOBAL_ACHIEVEMENT.ARTIFACT_RECOVERED,
        complete: true,
      },
    ],
    goals: [{ type: GOAL.DESTROY }],
    effects: [{ type: EFFECT.ADD_X_CARDS, count: 3, card: ATTACK_MODIFIER_CARD.CURSE }],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.DOOM_TRENCH },
      { type: REWARD.SCENARIO, scenario: ID.SLAVE_PENS },
      { type: REWARD.SCENARIO, scenario: ID.TREACHEROUS_DIVIDE },
      { type: REWARD.SCENARIO, scenario: ID.DRAKE_NEST },
      { type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.ARTIFACT_CLEANSED },
    ],
  },
  [ID.DECREPIT_WOOD]: {
    id: ID.DECREPIT_WOOD,
    name: 'Decrepit Wood',
    region: REGION.LINGERING_SWAMP,
    links: [],
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT,
        achievement: PARTY_ACHIEVEMENT.THE_VOICES_COMMAND,
        complete: true,
      },
    ],
    goals: [{ type: GOAL.REVEAL }, { type: GOAL.KILL_ALL_REVEALED_ENEMIES }, { type: GOAL.LOOT_ALL_TREASURE_TILES }],
    effects: [],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.SAVVAS_ARMORY },
      { type: REWARD.SCENARIO, scenario: ID.ANCIENT_DEFENSE_NETWORK },
    ],
  },
  [ID.SAVVAS_ARMORY]: {
    id: ID.SAVVAS_ARMORY,
    name: 'Savvas Armory',
    region: REGION.COPPERNECK_MOUNTAINS,
    links: [],
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.ONE_OF,
        condition: [
          {
            type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT,
            achievement: PARTY_ACHIEVEMENT.THE_VOICES_COMMAND,
            complete: true,
          },
          {
            type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT,
            achievement: PARTY_ACHIEVEMENT.THE_DRAKES_COMMAND,
            complete: true,
          },
        ],
      },
    ],
    goals: [{ type: GOAL.LOOT_ALL_TREASURE_TILES }, { type: GOAL.EXIT }],
    effects: [],
    rewards: [
      { type: REWARD.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.THE_VOICES_TREASURE },
      { type: REWARD.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.THE_DRAKES_TREASURE },
    ],
  },
  [ID.SCORCHED_SUMMIT]: {
    id: ID.SCORCHED_SUMMIT,
    name: 'Scorched Summit',
    boss: true,
    region: REGION.COPPERNECK_MOUNTAINS,
    links: [ID.ICECRAG_ASCENT],
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT,
        achievement: PARTY_ACHIEVEMENT.THE_DRAKES_COMMAND,
        complete: true,
      },
      {
        type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
        achievement: GLOBAL_ACHIEVEMENT.THE_DRAKE_AIDED,
        complete: false,
      },
    ],
    goals: [{ type: GOAL.KILL_ENEMY, enemy: ENEMY.ELDER_DRAKE }],
    effects: [],
    rewards: [
      { type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.THE_DRAKE_SLAIN },
      { type: REWARD.LOST_PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.THE_DRAKES_COMMAND },
      { type: REWARD.GOLD, count: 20 },
      { type: REWARD.REPUTATION, count: 2 },
      { type: REWARD.PROSPERITY, count: 1 },
    ],
  },
  [ID.GLOOMHAVEN_BATTLEMENTS_A]: {
    id: ID.GLOOMHAVEN_BATTLEMENTS_A,
    name: 'Gloomhaven Battlements A',
    boss: true,
    region: REGION.GLOOMHAVEN,
    links: gloomhavenLinks(ID.GLOOMHAVEN_BATTLEMENTS_A),
    linksGloomhaven: true,
    requirements: [
      { type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.A_DEMONS_ERRAND, complete: true },
      {
        type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
        achievement: GLOBAL_ACHIEVEMENT.THE_RIFT_NEUTRALIZED,
        complete: false,
      },
    ],
    goals: [{ type: GOAL.DESTROY }, { type: GOAL.KILL_ENEMY, enemy: ENEMY.CAPTAIN_OF_THE_GUARD }],
    effects: [],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.REBEL_SWAMP },
      { type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.CITY_RULE_DEMONIC },
      { type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.ARTIFACT_LOST },
      { type: REWARD.LOST_PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.A_DEMONS_ERRAND },
      { type: REWARD.GOLD, count: 30 },
      { type: REWARD.REPUTATION, count: -5 },
      { type: REWARD.PROSPERITY, count: -2 },
      { type: REWARD.CITY_EVENT, event: 79 },
    ],
  },
  [ID.GLOOMHAVEN_BATTLEMENTS_B]: {
    id: ID.GLOOMHAVEN_BATTLEMENTS_B,
    name: 'Gloomhaven Battlements B',
    boss: true,
    region: REGION.GLOOMHAVEN,
    links: gloomhavenLinks(ID.GLOOMHAVEN_BATTLEMENTS_B),
    linksGloomhaven: true,
    requirements: [
      { type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.A_DEMONS_ERRAND, complete: true },
      {
        type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
        achievement: GLOBAL_ACHIEVEMENT.THE_RIFT_NEUTRALIZED,
        complete: false,
      },
    ],
    goals: [{ type: GOAL.KILL_ENEMY, enemy: ENEMY.PRIME_DEMON }],
    effects: [],
    rewards: [
      { type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.THE_RIFT_NEUTRALIZED },
      { type: REWARD.LOST_PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.A_DEMONS_ERRAND },
      { type: REWARD.GOLD, count: 10 },
      { type: REWARD.REPUTATION, count: 4 },
      { type: REWARD.CITY_EVENT, event: 78 },
    ],
  },
  [ID.DOOM_TRENCH]: {
    id: ID.DOOM_TRENCH,
    name: 'Doom Trench',
    region: REGION.MISTY_SEA,
    links: gloomhavenLinks(ID.DOOM_TRENCH),
    linksGloomhaven: true,
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
        achievement: GLOBAL_ACHIEVEMENT.WATER_BREATHING,
        complete: true,
      },
    ],
    goals: [{ type: GOAL.EXIT }],
    effects: [{ type: EFFECT.ADD_X_CARDS, count: 3, card: ATTACK_MODIFIER_CARD.CURSE }],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.LAIR_OF_THE_UNSEEING_EYE },
      { type: REWARD.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.THROUGH_THE_TRENCH },
    ],
  },
  [ID.SLAVE_PENS]: {
    id: ID.SLAVE_PENS,
    name: 'Slave Pens',
    region: REGION.DAGGER_FOREST,
    links: [ID.TRIBAL_ASSAULT],
    requirements: [],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }, { type: GOAL.PROTECT }],
    effects: [],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.TRIBAL_ASSAULT },
      { type: REWARD.SCENARIO, scenario: ID.SHADOW_WEALD },
      { type: REWARD.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.REDTHORNS_AID },
      { type: REWARD.REPUTATION, count: 1 },
    ],
  },
  [ID.TREACHEROUS_DIVIDE]: {
    id: ID.TREACHEROUS_DIVIDE,
    name: 'Treacherous Divide',
    region: REGION.COPPERNECK_MOUNTAINS,
    links: [ID.NIGHTMARE_PEAK],
    requirements: [],
    goals: [{ type: GOAL.DESTROY }],
    effects: [{ type: EFFECT.ADD_X_CARDS, count: 3, card: ATTACK_MODIFIER_CARD.CURSE }],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.SHRINE_OF_STRENGTH },
      { type: REWARD.SCENARIO, scenario: ID.NIGHTMARE_PEAK },
      { type: REWARD.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.ACROSS_THE_DIVIDE },
      { type: REWARD.XP, count: 10 },
    ],
  },
  [ID.ANCIENT_DEFENSE_NETWORK]: {
    id: ID.ANCIENT_DEFENSE_NETWORK,
    name: 'Ancient Defense Network',
    region: REGION.COPPERNECK_MOUNTAINS,
    links: [ID.TIMEWORN_TOMB],
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT,
        achievement: PARTY_ACHIEVEMENT.THE_VOICES_COMMAND,
        complete: true,
      },
      {
        type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT,
        achievement: PARTY_ACHIEVEMENT.THE_VOICES_TREASURE,
        complete: true,
      },
    ],
    goals: [{ type: GOAL.OCCUPY }],
    effects: [{ type: EFFECT.ADD_X_CARDS, count: 3, card: ATTACK_MODIFIER_CARD.NEG1 }],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.TIMEWORN_TOMB },
      { type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.ANCIENT_TECHNOLOGY },
    ],
  },
  [ID.TIMEWORN_TOMB]: {
    id: ID.TIMEWORN_TOMB,
    name: 'Timeworn Tomb',
    region: REGION.COPPERNECK_MOUNTAINS,
    links: [ID.ANCIENT_DEFENSE_NETWORK],
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT,
        achievement: PARTY_ACHIEVEMENT.THE_VOICES_COMMAND,
        complete: true,
      },
    ],
    goals: [{ type: GOAL.EXIT }],
    effects: [],
    rewards: [
      { type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.THE_VOICE_FREED },
      { type: REWARD.GOLD, count: 50 },
      { type: REWARD.XP, count: 25 },
      { type: REWARD.CHECKMARKS, count: 2 },
      { type: REWARD.PROSPERITY, count: 2 },
    ],
  },
  [ID.REALM_OF_THE_VOICE]: {
    id: ID.REALM_OF_THE_VOICE,
    name: 'Realm of the Voice',
    region: REGION.COPPERNECK_MOUNTAINS,
    links: [],
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT,
        achievement: PARTY_ACHIEVEMENT.THE_SCEPTER_AND_THE_VOICE,
        complete: true,
      },
      {
        type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
        achievement: GLOBAL_ACHIEVEMENT.THE_VOICE_FREED,
        complete: false,
      },
    ],
    goals: [{ type: GOAL.DESTROY }],
    effects: [],
    rewards: [
      { type: REWARD.LOST_PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.THE_VOICES_COMMAND },
      { type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.THE_VOICE_SILENCED },
    ],
  },
  [ID.DRAKE_NEST]: {
    id: ID.DRAKE_NEST,
    name: 'Drake Nest',
    region: REGION.DAGGER_FOREST,
    links: [],
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
        achievement: GLOBAL_ACHIEVEMENT.THE_POWER_OF_ENHANCEMENT,
        complete: true,
      },
    ],
    goals: [{ type: GOAL.KILL_X_TIMES_CHARACTERS_ENEMIES, count: 4 }],
    effects: [],
    rewards: [{ type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.WATER_BREATHING }],
  },
  [ID.TRIBAL_ASSAULT]: {
    id: ID.TRIBAL_ASSAULT,
    name: 'Tribal Assault',
    region: REGION.DAGGER_FOREST,
    links: [ID.SLAVE_PENS],
    requirements: [
      { type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.REDTHORNS_AID, complete: true },
    ],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }, { type: GOAL.PROTECT }],
    effects: [],
    rewards: [{ type: REWARD.CLASS, class: CLASS.DOOMSTALKER }, { type: REWARD.REPUTATION, count: 2 }],
  },
  [ID.REBEL_SWAMP]: {
    id: ID.REBEL_SWAMP,
    name: 'Rebel Swamp',
    region: REGION.LINGERING_SWAMP,
    links: [],
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
        achievement: GLOBAL_ACHIEVEMENT.CITY_RULE_DEMONIC,
        complete: true,
      },
    ],
    goals: [{ type: GOAL.DESTROY }],
    effects: [{ type: EFFECT.ADD_X_CARDS, count: 2, card: ATTACK_MODIFIER_CARD.NEG1 }],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.REBELS_STAND },
      { type: REWARD.SCENARIO, scenario: ID.GHOST_FORTRESS },
      { type: REWARD.GOLD, count: 20 },
      { type: REWARD.REPUTATION, count: -2 },
    ],
  },
  [ID.NIGHTMARE_PEAK]: {
    id: ID.NIGHTMARE_PEAK,
    name: 'Nightmare Peak',
    boss: true,
    region: REGION.COPPERNECK_MOUNTAINS,
    links: [ID.TREACHEROUS_DIVIDE],
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT,
        achievement: PARTY_ACHIEVEMENT.ACROSS_THE_DIVIDE,
        complete: true,
      },
    ],
    goals: [{ type: GOAL.KILL_ENEMY, enemy: ENEMY.WINGED_HORROR }],
    effects: [],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.THE_VOID },
      { type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.END_OF_CORRUPTION },
    ],
  },
  [ID.LAIR_OF_THE_UNSEEING_EYE]: {
    id: ID.LAIR_OF_THE_UNSEEING_EYE,
    name: 'Lair of the Unseeing Eye',
    boss: true,
    region: REGION.MISTY_SEA,
    links: gloomhavenLinks(ID.LAIR_OF_THE_UNSEEING_EYE),
    linksGloomhaven: true,
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT,
        achievement: PARTY_ACHIEVEMENT.THROUGH_THE_TRENCH,
        complete: true,
      },
    ],
    goals: [{ type: GOAL.KILL_ENEMY, enemy: ENEMY.SIGHTLESS_EYE }],
    effects: [{ type: EFFECT.ADD_X_CARDS, count: 3, card: ATTACK_MODIFIER_CARD.CURSE }],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.THE_VOID },
      { type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.END_OF_CORRUPTION },
    ],
  },
  [ID.SHADOW_WEALD]: {
    id: ID.SHADOW_WEALD,
    name: 'Shadow Weald',
    boss: true,
    region: REGION.DAGGER_FOREST,
    links: [],
    requirements: [
      { type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.REDTHORNS_AID, complete: true },
    ],
    goals: [{ type: GOAL.KILL_ENEMY, enemy: ENEMY.DARK_RIDER }],
    effects: [{ type: EFFECT.MUDDLE }],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.THE_VOID },
      { type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.END_OF_CORRUPTION },
    ],
  },
  [ID.REBELS_STAND]: {
    id: ID.REBELS_STAND,
    name: "Rebel's Stand",
    region: REGION.LINGERING_SWAMP,
    links: [],
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
        achievement: GLOBAL_ACHIEVEMENT.CITY_RULE_DEMONIC,
        complete: true,
      },
    ],
    goals: [{ type: GOAL.KILL_ENEMY, enemy: ENEMY.SIEGE_CANNON }],
    effects: [],
    rewards: [
      { type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.ANNIHILATION_OF_ORDER },
      { type: REWARD.GOLD, count: 50 },
      { type: REWARD.REPUTATION, count: -3 },
    ],
  },
  [ID.GHOST_FORTRESS]: {
    id: ID.GHOST_FORTRESS,
    name: 'Ghost Fortress',
    region: REGION.GLOOMHAVEN,
    links: gloomhavenLinks(ID.GHOST_FORTRESS),
    linksGloomhaven: true,
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
        achievement: GLOBAL_ACHIEVEMENT.CITY_RULE_DEMONIC,
        complete: true,
      },
      {
        type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
        achievement: GLOBAL_ACHIEVEMENT.ANNIHILATION_OF_ORDER,
        complete: false,
      },
    ],
    goals: [{ type: GOAL.LOOT_ALL_TREASURE_TILES }],
    effects: [],
    rewards: [
      { type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.CITY_RULE_MILITARISTIC },
      { type: REWARD.REPUTATION, count: 3 },
      { type: REWARD.PROSPERITY, count: -2 },
    ],
  },
  [ID.THE_VOID]: {
    id: ID.THE_VOID,
    name: 'The Void',
    boss: true,
    region: REGION.GLOOMHAVEN,
    links: gloomhavenLinks(ID.THE_VOID),
    linksGloomhaven: true,
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
        achievement: GLOBAL_ACHIEVEMENT.END_OF_CORRUPTION,
        complete: true,
        min: 3,
      },
    ],
    goals: [{ type: GOAL.KILL_ENEMY, enemy: ENEMY.GLOOM }],
    effects: [{ type: EFFECT.ADD_X_CARDS, count: 3, card: ATTACK_MODIFIER_CARD.CURSE }],
    rewards: [
      { type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.END_OF_GLOOM },
      { type: REWARD.REPUTATION, count: 5 },
      { type: REWARD.PROSPERITY, count: 5 },
      { type: REWARD.CITY_EVENT, event: 81 },
      { type: REWARD.ROAD_EVENT, event: 69 },
    ],
  },
  [ID.NOXIOUS_CELLAR]: {
    id: ID.NOXIOUS_CELLAR,
    name: 'Noxious Cellar',
    region: REGION.GLOOMHAVEN,
    links: gloomhavenLinks(ID.NOXIOUS_CELLAR),
    linksGloomhaven: true,
    requirements: [{ type: SCENARIO_REQUIREMENT.PERSONAL_QUEST, quest: PERSONAL_QUEST.SEEKER_OF_XORN }],
    goals: [{ type: GOAL.ALL_CHARACTERS_LOOT_TREASURE }],
    effects: [{ type: EFFECT.ADD_X_CARDS, count: 2, card: ATTACK_MODIFIER_CARD.CURSE }],
    rewards: [{ type: REWARD.SCENARIO, scenario: ID.CRYPT_BASEMENT }],
  },
  [ID.CRYPT_BASEMENT]: {
    id: ID.CRYPT_BASEMENT,
    name: 'Crypt Basement',
    region: REGION.UNKNOWN,
    crypt: true,
    links: [],
    requirements: [{ type: SCENARIO_REQUIREMENT.PERSONAL_QUEST, quest: PERSONAL_QUEST.SEEKER_OF_XORN }],
    goals: [{ type: GOAL.SURVIVE_X_ROUNDS, count: 10 }],
    effects: [{ type: EFFECT.ADD_X_CARDS, count: 3, card: ATTACK_MODIFIER_CARD.CURSE }],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.PALACE_OF_ICE },
      {
        type: REWARD.ITEM,
        item: ITEM.STAFF_OF_XORN,
        note: 'The Seeker of Xorn receives the staff.  The Seeker cannot sell this item.',
      },
    ],
  },
  [ID.PALACE_OF_ICE]: {
    id: ID.PALACE_OF_ICE,
    name: 'Palace of Ice',
    region: REGION.COPPERNECK_MOUNTAINS,
    links: [],
    requirements: [
      { type: SCENARIO_REQUIREMENT.PERSONAL_QUEST, quest: PERSONAL_QUEST.SEEKER_OF_XORN },
      { type: SCENARIO_REQUIREMENT.ITEM_EQUIPPED, item: ITEM.STAFF_OF_XORN },
    ],
    goals: [{ type: GOAL.PLACE_ITEM }],
    effects: [],
    rewards: [
      { type: REWARD.RETIRE, note: 'Immediately retire the Seeker of Xorn.' },
      { type: REWARD.CITY_EVENT, event: 59, note: 'Instead of normal retirment events.' },
      { type: REWARD.ROAD_EVENT, event: 59, note: 'Instead of normal retirement events.' },
      { type: REWARD.CLASS, class: CLASS.PLAGUEHERALD },
    ],
  },
  [ID.FOGGY_THICKET]: {
    id: ID.FOGGY_THICKET,
    name: 'Foggy Thicket',
    region: REGION.DAGGER_FOREST,
    links: [ID.BANDITS_WOOD],
    requirements: [{ type: SCENARIO_REQUIREMENT.PERSONAL_QUEST, quest: PERSONAL_QUEST.TAKE_BACK_THE_TREES }],
    goals: [{ type: GOAL.LOOT_ALL_TREASURE_TILES }],
    effects: [{ type: EFFECT.ADD_X_CARDS, count: 3, card: ATTACK_MODIFIER_CARD.NEG1 }],
    rewards: [{ type: REWARD.SCENARIO, scenario: ID.BANDITS_WOOD }, { type: REWARD.COLLECTIVE_GOLD, count: 10 }],
  },
  [ID.BANDITS_WOOD]: {
    id: ID.BANDITS_WOOD,
    name: "Bandit's Wood",
    region: REGION.DAGGER_FOREST,
    links: [ID.FOGGY_THICKET],
    requirements: [{ type: SCENARIO_REQUIREMENT.PERSONAL_QUEST, quest: PERSONAL_QUEST.TAKE_BACK_THE_TREES }],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }, { type: GOAL.PROTECT }],
    effects: [],
    rewards: [
      { type: REWARD.CLASS, class: CLASS.DOOMSTALKER, note: '"Take Back the Trees" quest complete.' },
      { type: REWARD.GOLD, count: 10 },
      { type: REWARD.REPUTATION, count: 2 },
    ],
  },
  [ID.INVESTIGATION]: {
    id: ID.INVESTIGATION,
    name: 'Investigation',
    region: REGION.GLOOMHAVEN,
    links: gloomhavenLinks(ID.INVESTIGATION),
    linksGloomhaven: true,
    requirements: [{ type: SCENARIO_REQUIREMENT.PERSONAL_QUEST, quest: PERSONAL_QUEST.VENGEANCE }],
    goals: [{ type: GOAL.KILL_ENEMY, enemy: ENEMY.INFILTRATOR }],
    effects: [],
    rewards: [{ type: REWARD.SCENARIO, scenario: ID.BLOODY_SHACK }, { type: REWARD.REPUTATION, count: 1 }],
  },
  [ID.BLOODY_SHACK]: {
    id: ID.BLOODY_SHACK,
    name: 'Bloody Shack',
    region: REGION.GLOOMHAVEN,
    links: gloomhavenLinks(ID.BLOODY_SHACK),
    linksGloomhaven: true,
    requirements: [{ type: SCENARIO_REQUIREMENT.PERSONAL_QUEST, quest: PERSONAL_QUEST.VENGEANCE }],
    goals: [{ type: GOAL.KILL_ENEMY, enemy: ENEMY.HARVESTER }],
    effects: [],
    rewards: [
      { type: REWARD.ENVELOPE, envelope: ENVELOPE.X, note: '"Vengeance" quest complete.' },
      { type: REWARD.REPUTATION, count: 2 },
    ],
  },
  [ID.FORGOTTEN_GROVE]: {
    id: ID.FORGOTTEN_GROVE,
    name: 'Forgotten Grove',
    region: REGION.DAGGER_FOREST,
    links: [],
    requirements: [{ type: SCENARIO_REQUIREMENT.PERSONAL_QUEST, quest: PERSONAL_QUEST.FINDING_THE_CURE }],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }, { type: GOAL.LOOT_ALL_TREASURE_TILES }],
    effects: [],
    rewards: [{ type: REWARD.SCENARIO, scenario: ID.ALCHEMY_LAB }],
  },
  [ID.ALCHEMY_LAB]: {
    id: ID.ALCHEMY_LAB,
    name: 'Alchemy Lab',
    region: REGION.GLOOMHAVEN,
    links: gloomhavenLinks(ID.ALCHEMY_LAB),
    linksGloomhaven: true,
    requirements: [{ type: SCENARIO_REQUIREMENT.PERSONAL_QUEST, quest: PERSONAL_QUEST.FINDING_THE_CURE }],
    goals: [{ type: GOAL.LOOT_ALL_TREASURE_TILES }, { type: GOAL.EXIT }],
    effects: [],
    rewards: [
      { type: REWARD.ENVELOPE, envelope: ENVELOPE.X, note: '"Finding the Cure" quest complete.' },
      { type: REWARD.REPUTATION, count: 1 },
    ],
  },
  [ID.FADING_LIGHTHOUSE]: {
    id: ID.FADING_LIGHTHOUSE,
    name: 'Fading Lighthouse',
    region: REGION.LINGERING_SWAMP,
    links: [ID.PIT_OF_SOULS],
    requirements: [{ type: SCENARIO_REQUIREMENT.PERSONAL_QUEST, quest: PERSONAL_QUEST.THE_FALL_OF_MAN }],
    goals: [{ type: GOAL.LOOT_ALL_TREASURE_TILES }],
    effects: [],
    rewards: [{ type: REWARD.SCENARIO, scenario: ID.PIT_OF_SOULS }],
  },
  [ID.PIT_OF_SOULS]: {
    id: ID.PIT_OF_SOULS,
    name: 'Pit of Souls',
    region: REGION.LINGERING_SWAMP,
    links: [ID.FADING_LIGHTHOUSE],
    requirements: [{ type: SCENARIO_REQUIREMENT.PERSONAL_QUEST, quest: PERSONAL_QUEST.THE_FALL_OF_MAN }],
    goals: [{ type: GOAL.KILL_ENEMY, enemy: ENEMY.HUNGRY_SOUL }],
    effects: [],
    rewards: [
      { type: REWARD.CLASS, class: CLASS.NIGHTSHROUD, note: '"The Fall of Man" quest complete.' },
      { type: REWARD.XP, count: 10 },
    ],
  },
  [ID.MAGMA_PIT]: {
    id: ID.MAGMA_PIT,
    name: 'Magma Pit',
    region: REGION.WATCHER_MOUNTAINS,
    links: [],
    requirements: [],
    goals: [{ kill: GOAL.KILL_ALL_ENEMIES }],
    effects: [{ type: EFFECT.WOUND }],
    rewards: [{ type: REWARD.GOLD, count: 15 }],
  },
  [ID.UNDERWATER_LAGOON]: {
    id: ID.UNDERWATER_LAGOON,
    name: 'Underwater Lagoon',
    region: REGION.MISTY_SEA,
    links: gloomhavenLinks(ID.UNDERWATER_LAGOON),
    linksGloomhaven: true,
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
        achievement: GLOBAL_ACHIEVEMENT.WATER_BREATHING,
        complete: true,
      },
    ],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }],
    effects: [],
    rewards: [{ type: REWARD.XP, count: 10 }],
  },
  [ID.SULFUR_MINE]: {
    id: ID.SULFUR_MINE,
    name: 'Sulfur Mine',
    region: REGION.WATCHER_MOUNTAINS,
    links: [],
    requirements: [],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }, { type: GOAL.LOOT_ALL_TREASURE_TILES }],
    effects: [{ type: EFFECT.ADD_X_CARDS, count: 4, card: ATTACK_MODIFIER_CARD.CURSE }],
    rewards: [
      { type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.ANCIENT_TECHNOLOGY },
      { type: REWARD.ITEM_DESIGN, item: ITEM.ANCIENT_DRILL },
    ],
  },
  [ID.CLOCKWORK_COVE]: {
    id: ID.CLOCKWORK_COVE,
    name: 'Clockwork Cove',
    region: REGION.COPPERNECK_MOUNTAINS,
    links: gloomhavenLinks(ID.CLOCKWORK_COVE),
    linksGloomhaven: true,
    requirements: [],
    goals: [{ type: GOAL.OCCUPY }],
    effects: [],
    rewards: [{ type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.ANCIENT_TECHNOLOGY }],
  },
  [ID.ARCANE_LIBRARY]: {
    id: ID.ARCANE_LIBRARY,
    name: 'Arcane Library',
    region: REGION.UNKNOWN,
    links: [],
    requirements: [],
    goals: [{ type: GOAL.KILL_ENEMY, enemy: ENEMY.ARCANE_GOLEM }],
    rewards: [
      { type: REWARD.GLOBAL_ACHIEVEMENT, achievement: GLOBAL_ACHIEVEMENT.ANCIENT_TECHNOLOGY },
      { type: REWARD.ITEM, item: ITEM.POWER_CORE },
    ],
  },
  [ID.TOXIC_MOOR]: {
    id: ID.TOXIC_MOOR,
    name: 'Toxic Moor',
    region: REGION.LINGERING_SWAMP,
    links: [],
    requirements: [],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }, { type: GOAL.PROTECT }],
    effects: [{ type: EFFECT.POISON }],
    rewards: [{ type: REWARD.ITEM_2X, item: ITEM.MAJOR_HEALING_POTION }],
  },
  [ID.WELL_OF_UNFORTUNATE]: {
    id: ID.WELL_OF_UNFORTUNATE,
    name: 'Well of Unfortunate',
    region: REGION.UNKNOWN,
    links: [],
    requirements: [],
    goals: [{ type: GOAL.PLACE_ITEM }],
    effects: [],
    rewards: [{ type: REWARD.GOLD, count: 15 }],
  },
  [ID.CHAINED_ISLE]: {
    id: ID.CHAINED_ISLE,
    name: 'Chained Isle',
    region: REGION.MISTY_SEA,
    links: gloomhavenLinks(ID.CHAINED_ISLE),
    linksGloomhaven: true,
    requirements: [],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }],
    effects: [],
    rewards: [{ type: REWARD.PROSPERITY, count: 2 }],
  },
  [ID.WINDSWEPT_HIGHLANDS]: {
    id: ID.WINDSWEPT_HIGHLANDS,
    name: 'Windswept Highlands',
    region: REGION.UNKNOWN,
    links: [],
    requirements: [],
    goals: [{ type: GOAL.LOOT_ALL_TREASURE_TILES }, { type: GOAL.EXIT }],
    effects: [],
    rewards: [{ type: REWARD.ITEM_2X, item: ITEM.MAJOR_POWER_POTION }],
  },
  [ID.OOZING_GROVE]: {
    id: ID.OOZING_GROVE,
    name: 'Oozing Grove',
    region: REGION.UNKNOWN,
    links: [],
    requirements: [],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }],
    effects: [],
    rewards: [{ type: REWARD.REPUTATION, count: 1 }, { type: REWARD.PROSPERITY, count: 1 }],
  },
  [ID.ROCKSLIDE_RIDGE]: {
    id: ID.ROCKSLIDE_RIDGE,
    name: 'Rockslide Ridge',
    region: REGION.WATCHER_MOUNTAINS,
    links: [],
    requirements: [],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }, { type: GOAL.LOOT_ALL_TREASURE_TILES }],
    effects: [],
    rewards: [{ type: REWARD.REPUTATION, count: 1 }],
  },
  [ID.MERCHANT_SHIP]: {
    id: ID.MERCHANT_SHIP,
    name: 'Merchant Ship',
    region: REGION.MISTY_SEA,
    links: gloomhavenLinks(ID.MERCHANT_SHIP),
    linksGloomhaven: true,
    requirements: [
      { type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.HIGH_SEA_ESCORT, complete: true },
    ],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }],
    effects: [],
    rewards: [{ type: REWARD.GOLD, count: 10 }, { type: REWARD.PROSPERITY, count: 1 }],
  },
  [ID.OVERGROWN_GRAVEYARD]: {
    id: ID.OVERGROWN_GRAVEYARD,
    name: 'Overgrown Graveyard',
    region: REGION.UNKNOWN,
    links: [],
    requirements: [
      { type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.GRAVE_JOB, complete: true },
    ],
    goals: [{ type: GOAL.KILL_ENEMY, enemy: ENEMY.BLOATED_REGENT }],
    effects: [],
    rewards: [{ type: REWARD.GOLD, count: 60 }],
  },
  [ID.HARROWER_HIVE]: {
    id: ID.HARROWER_HIVE,
    name: 'Harrower Hive',
    region: REGION.WATCHER_MOUNTAINS,
    links: [],
    requirements: [{ type: SCENARIO_REQUIREMENT.BRAVERY }],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }],
    effects: [],
    rewards: [],
  },
  [ID.VAULT_OF_SECRETS]: {
    id: ID.VAULT_OF_SECRETS,
    name: 'Vault of Secrets',
    region: REGION.GLOOMHAVEN,
    links: gloomhavenLinks(ID.VAULT_OF_SECRETS),
    linksGloomhaven: true,
    requirements: [],
    goals: [{ type: GOAL.LOOT_ALL_TREASURE_TILES }, { type: GOAL.KILL_ALL_ENEMIES }],
    effects: [],
    rewards: [{ type: REWARD.XP, count: 5 }],
  },
  [ID.SACRIFICE_PIT]: {
    id: ID.SACRIFICE_PIT,
    name: 'Sacrifice Pit',
    region: REGION.GLOOMHAVEN,
    links: gloomhavenLinks(ID.SACRIFICE_PIT),
    linksGloomhaven: true,
    requirements: [],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }],
    effects: [],
    rewards: [{ type: REWARD.REPUTATION, count: 3 }],
  },
  [ID.LOST_TEMPLE]: {
    id: ID.LOST_TEMPLE,
    name: 'Lost Temple',
    boss: true,
    region: REGION.LINGERING_SWAMP,
    links: [],
    requirements: [
      { type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.FISHS_AID, complete: true },
    ],
    goals: [{ kill: GOAL.KILL_ENEMY, enemy: ENEMY.BETRAYER }],
    effects: [],
    rewards: [{ type: REWARD.GOLD, count: 15 }],
  },
  [ID.VIGIL_KEEP]: {
    id: ID.VIGIL_KEEP,
    name: 'Vigil Keep',
    region: REGION.WATCHER_MOUNTAINS,
    links: [],
    requirements: [],
    goals: [{ type: GOAL.ALL_CHARACTERS_LOOT_TREASURE }, { type: GOAL.EXIT }],
    effects: [],
    rewards: [{ type: REWARD.XP, count: 10 }],
  },
  [ID.TEMPLE_OF_THE_ECLIPSE]: {
    id: ID.TEMPLE_OF_THE_ECLIPSE,
    name: 'Temple of the Eclipse',
    boss: true,
    region: REGION.DAGGER_FOREST,
    links: [],
    requirements: [],
    goals: [{ kill: GOAL.KILL_ENEMY, enemy: ENEMY.COLORLESS }],
    effects: [],
    rewards: [{ type: REWARD.XP, count: 10 }],
  },
  [ID.BURNING_MOUNTAIN]: {
    id: ID.BURNING_MOUNTAIN,
    name: 'Burning Mountain',
    region: REGION.WATCHER_MOUNTAINS,
    links: [],
    requirements: [],
    goals: [],
    effects: [],
    rewards: [
      {
        type: REWARD.EITHER,
        a: [{ type: REWARD.REPUTATION, count: 1 }],
        b: [{ type: REWARD.REPUTATION, count: -1 }, { type: REWARD.PROSPERITY, count: -2 }],
      },
    ],
  },
  [ID.SHADOWS_WITHIN]: {
    id: ID.SHADOWS_WITHIN,
    name: 'Shadows Within',
    region: REGION.GLOOMHAVEN,
    links: gloomhavenLinks(ID.SHADOWS_WITHIN),
    linksGloomhaven: true,
    requirements: [
      { type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.BAD_BUSINESS, complete: true },
    ],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }],
    effects: [],
    rewards: [{ type: REWARD.COLLECTIVE_GOLD, count: 40 }],
  },
  [ID.CRYSTALLINE_CAVE]: {
    id: ID.CRYSTALLINE_CAVE,
    name: 'Crystalline Cave',
    region: REGION.COPPERNECK_MOUNTAINS,
    links: [],
    requirements: [
      { type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.TREMORS, complete: true },
    ],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }, { type: GOAL.PROTECT }],
    effects: [],
    rewards: [{ type: REWARD.ITEM, item: ITEM.RESONANT_CRYSTAL }, { type: REWARD.PROSPERITY, count: 1 }],
  },
  [ID.SUN_TEMPLE]: {
    id: ID.SUN_TEMPLE,
    name: 'Sun Temple',
    region: REGION.WATCHER_MOUNTAINS,
    links: [],
    requirements: [],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }],
    effects: [],
    rewards: [{ type: REWARD.ITEM, item: ITEM.ORB_OF_DAWN }],
  },
  [ID.HARRIED_VILLAGE]: {
    id: ID.HARRIED_VILLAGE,
    name: 'Harried Village',
    region: REGION.GLOOMHAVEN,
    links: gloomhavenLinks(ID.HARRIED_VILLAGE),
    linksGloomhaven: true,
    requirements: [],
    goals: [],
    effects: [],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.CORRUPTED_COVE },
      { type: REWARD.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.THE_POISONS_SOURCE },
      { type: REWARD.REPUTATION, count: 2 },
    ],
  },
  [ID.CORRUPTED_COVE]: {
    id: ID.CORRUPTED_COVE,
    name: 'Corrupted Cove',
    region: REGION.UNKNOWN,
    links: gloomhavenLinks(ID.CORRUPTED_COVE),
    linksGloomhaven: true,
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT,
        achievement: PARTY_ACHIEVEMENT.THE_POISONS_SOURCE,
        complete: true,
      },
    ],
    goals: [{ type: GOAL.KILL_ENEMY, enemy: ENEMY.GIANT_OOZE }],
    rewards: [{ type: REWARD.REPUTATION, count: 1 }, { type: REWARD.PROSPERITY, count: 1 }],
  },
  [ID.PLANE_OF_WATER]: {
    id: ID.PLANE_OF_WATER,
    name: 'Plane of Water',
    region: REGION.GLOOMHAVEN,
    links: gloomhavenLinks(ID.PLANE_OF_WATER),
    linksGloomhaven: true,
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.GLOBAL_ACHIEVEMENT,
        achievement: GLOBAL_ACHIEVEMENT.WATER_BREATHING,
        complete: true,
      },
      { type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.WATER_STAFF, complete: true },
    ],
    goals: [{ type: GOAL.PLACE_ITEM }],
    effects: [],
    rewards: [{ type: REWARD.ITEM, item: ITEM.STAFF_OF_SUMMONING }],
  },
  [ID.SYNDICATE_HIDEOUT]: {
    id: ID.SYNDICATE_HIDEOUT,
    name: 'Syndicate Hideout',
    region: REGION.GLOOMHAVEN,
    links: gloomhavenLinks(ID.SYNDICATE_HIDEOUT),
    linksGloomhaven: true,
    requirements: [
      { type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.SIN_RA, complete: true },
    ],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }],
    effects: [],
    rewards: [{ type: REWARD.COLLECTIVE_GOLD, count: 50 }],
  },
  [ID.DEMONIC_RIFT]: {
    id: ID.DEMONIC_RIFT,
    name: 'Demonic Rift',
    region: REGION.UNKNOWN,
    links: [],
    requirements: [],
    goals: [],
    effects: [],
    rewards: [{ type: REWARD.ITEM, item: ITEM.BLACK_CENSER }],
  },
  [ID.WILD_MELEE]: {
    id: ID.WILD_MELEE,
    name: 'Wild Melee',
    region: REGION.DAGGER_FOREST,
    links: [],
    requirements: [],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }],
    effects: [],
    rewards: [{ type: REWARD.CHECKMARKS, count: 2 }],
  },
  [ID.BACK_ALLEY_BRAWL]: {
    id: ID.BACK_ALLEY_BRAWL,
    name: 'Back Alley Brawl',
    region: REGION.GLOOMHAVEN,
    links: gloomhavenLinks(ID.BACK_ALLEY_BRAWL),
    linksGloomhaven: true,
    requirements: [
      { type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.DEBT_COLLECTION, complete: true },
    ],
    goals: [],
    effects: [],
    rewards: [{ type: REWARD.GOLD, count: 10 }, { type: REWARD.REPUTATION, count: -3 }],
  },
  [ID.SUNKEN_VESSEL]: {
    id: ID.SUNKEN_VESSEL,
    name: 'Sunken Vessel',
    region: REGION.MISTY_SEA,
    links: gloomhavenLinks(ID.SUNKEN_VESSEL),
    linksGloomhaven: true,
    requirements: [
      {
        type: SCENARIO_REQUIREMENT.PARTY_ACHIEVEMENT,
        achievement: PARTY_ACHIEVEMENT.A_MAP_TO_TREASURE,
        complete: true,
      },
    ],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }],
    effects: [{ type: EFFECT.IMMOBILIZE }],
    rewards: [{ type: REWARD.XP, count: 10 }],
  },
  [ID.VERMLING_NEST]: {
    id: ID.VERMLING_NEST,
    name: 'Vermling Nest',
    region: REGION.UNKNOWN,
    links: [ID.PAYMENT_DUE],
    requirements: [],
    goals: [{ type: GOAL.KILL_ALL_ENEMIES }, { type: GOAL.LOOT_ALL_TREASURE_TILES }],
    effects: [],
    rewards: [
      { type: REWARD.SCENARIO, scenario: ID.PAYMENT_DUE },
      { type: REWARD.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.THROUGH_THE_NEST },
    ],
  },
  [ID.PAYMENT_DUE]: {
    id: ID.PAYMENT_DUE,
    name: 'Payment Due',
    region: REGION.UNKNOWN,
    links: [ID.VERMLING_NEST],
    requirements: [{ type: REWARD.PARTY_ACHIEVEMENT, achievement: PARTY_ACHIEVEMENT.THROUGH_THE_NEST, complete: true }],
    goals: [{ type: GOAL.KILL_ENEMY, enemy: ENEMY.PRIME_LIEUTENANT }],
    rewards: [{ type: REWARD.ITEM, item: ITEM.SKULL_OF_HATRED }],
  },
  [ID.SOLO_BRUTE]: {
    id: ID.SOLO_BRUTE,
    name: 'Return to the Black Barrow',
    region: REGION.UNKNOWN,
    links: [],
    requirements: [],
    goals: [],
    rewards: [{ type: REWARD.ITEM, item: ITEM.IMPOSING_BLADE }],
    solo: true,
    class: CLASS.BRUTE,
  },
  [ID.SOLO_CRAGHEART]: {
    id: ID.SOLO_CRAGHEART,
    name: 'Stone Defense',
    region: REGION.UNKNOWN,
    links: [],
    requirements: [],
    goals: [],
    rewards: [{ type: REWARD.ITEM, item: ITEM.STONE_CHARM }],
    solo: true,
    class: CLASS.CRAGHEART,
  },
  [ID.SOLO_MINDTHIEF]: {
    id: ID.SOLO_MINDTHIEF,
    name: 'Rodent Liberation',
    region: REGION.UNKNOWN,
    links: [],
    requirements: [],
    goals: [],
    rewards: [{ type: REWARD.ITEM, item: ITEM.PSYCHIC_KNIFE }],
    solo: true,
    class: CLASS.MINDTHIEF,
  },
  [ID.SOLO_SCOUNDREL]: {
    id: ID.SOLO_SCOUNDREL,
    name: 'Armory Heist',
    region: REGION.UNKNOWN,
    links: [],
    requirements: [],
    goals: [],
    rewards: [{ type: REWARD.ITEM, item: ITEM.SILENT_STILETTO }],
    solo: true,
    class: CLASS.SCOUNDREL,
  },
  [ID.SOLO_SPELLWEAVER]: {
    id: ID.SOLO_SPELLWEAVER,
    name: 'Corrupted Laboratory',
    region: REGION.UNKNOWN,
    links: [],
    requirements: [],
    goals: [],
    rewards: [{ type: REWARD.ITEM, item: ITEM.VOLATILE_ELIXIR }],
    solo: true,
    class: CLASS.SPELLWEAVER,
  },
  [ID.SOLO_TINKERER]: {
    id: ID.SOLO_TINKERER,
    name: 'An Unfortunate Intrusion',
    region: REGION.UNKNOWN,
    links: [],
    requirements: [],
    goals: [],
    rewards: [{ type: REWARD.ITEM, item: ITEM.FOCUSING_RAY }],
    solo: true,
    class: CLASS.TINKERER,
  },
  [ID.SOLO_BERSERKER]: {
    id: ID.SOLO_BERSERKER,
    name: 'Unnatural Insults',
    region: REGION.UNKNOWN,
    links: [],
    requirements: [],
    goals: [],
    rewards: [{ type: REWARD.ITEM, item: ITEM.MASK_OF_DEATH }],
    solo: true,
    class: CLASS.BERSERKER,
  },
  [ID.SOLO_BEAST_TYRANT]: {
    id: ID.SOLO_BEAST_TYRANT,
    name: 'The Caged Bear',
    region: REGION.UNKNOWN,
    links: [],
    requirements: [],
    goals: [],
    rewards: [{ type: REWARD.ITEM, item: ITEM.STAFF_OF_COMMAND }],
    solo: true,
    class: CLASS.BEAST_TYRANT,
  },
  [ID.SOLO_DOOMSTALKER]: {
    id: ID.SOLO_DOOMSTALKER,
    name: 'Corrupted Hunt',
    region: REGION.UNKNOWN,
    links: [],
    requirements: [],
    goals: [],
    rewards: [{ type: REWARD.ITEM, item: ITEM.CLOAK_OF_THE_HUNTER }],
    solo: true,
    class: CLASS.DOOMSTALKER,
  },
  [ID.SOLO_ELEMENTALIST]: {
    id: ID.SOLO_ELEMENTALIST,
    name: 'Elemental Secrets',
    region: REGION.UNKNOWN,
    links: [],
    requirements: [],
    goals: [],
    rewards: [{ type: REWARD.ITEM, item: ITEM.ELEMENTAL_BOOTS }],
    solo: true,
    class: CLASS.ELEMENTALIST,
  },
  [ID.SOLO_NIGHTSHROUD]: {
    id: ID.SOLO_NIGHTSHROUD,
    name: 'Harvesting the Night',
    region: REGION.UNKNOWN,
    links: [],
    requirements: [],
    goals: [],
    rewards: [{ type: REWARD.ITEM, item: ITEM.SMOKE_ELIXIR }],
    solo: true,
    class: CLASS.NIGHTSHROUD,
  },
  [ID.SOLO_PLAGUEHERALD]: {
    id: ID.SOLO_PLAGUEHERALD,
    name: 'Plagued Crypt',
    region: REGION.UNKNOWN,
    links: [],
    requirements: [],
    goals: [],
    rewards: [{ type: REWARD.ITEM, item: ITEM.PENDANT_OF_THE_PLAGUE }],
    solo: true,
    class: CLASS.PLAGUEHERALD,
  },
  [ID.SOLO_QUARTERMASTER]: {
    id: ID.SOLO_QUARTERMASTER,
    name: 'Storage Fees',
    region: REGION.UNKNOWN,
    links: [],
    requirements: [],
    goals: [],
    rewards: [{ type: REWARD.ITEM, item: ITEM.UTILITY_BELT }],
    solo: true,
    class: CLASS.QUARTERMASTER,
  },
  [ID.SOLO_SAWBONE]: {
    id: ID.SOLO_SAWBONE,
    name: 'Aftermath',
    region: REGION.UNKNOWN,
    links: [],
    requirements: [],
    goals: [],
    rewards: [{ type: REWARD.ITEM, item: ITEM.DOCTORS_COAT }],
    solo: true,
    class: CLASS.SAWBONE,
  },
  [ID.SOLO_SUNKEEPER]: {
    id: ID.SOLO_SUNKEEPER,
    name: 'Caravan Escort',
    region: REGION.UNKNOWN,
    links: [],
    requirements: [],
    goals: [],
    rewards: [{ type: REWARD.ITEM, item: ITEM.SUN_SHIELD }],
    solo: true,
    class: CLASS.SUNKEEPER,
  },
  [ID.SOLO_SOOTHSINGER]: {
    id: ID.SOLO_SOOTHSINGER,
    name: 'Battle of the Bards',
    region: REGION.UNKNOWN,
    links: [],
    requirements: [],
    goals: [],
    rewards: [{ type: REWARD.ITEM, item: ITEM.MASTERS_LUTE }],
    solo: true,
    class: CLASS.SOOTHSINGER,
  },
  [ID.SOLO_SUMMONER]: {
    id: ID.SOLO_SUMMONER,
    name: 'Plane of the Wild Beasts',
    region: REGION.UNKNOWN,
    links: [],
    requirements: [],
    goals: [],
    rewards: [{ type: REWARD.ITEM, item: ITEM.PHASING_IDOL }],
    solo: true,
    class: CLASS.SUMMONER,
  },
};

function gloomhavenLinks(id) {
  return [
    ID.GLOOMHAVEN_WAREHOUSE,
    ID.GLOOMHAVEN_SQUARE_A,
    ID.GLOOMHAVEN_SQUARE_B,
    ID.ABANDONED_SEWERS,
    ID.DEEP_RUINS,
    ID.ANCIENT_CISTERN,
    ID.PLANE_OF_NIGHT,
    ID.GLOOMHAVEN_BATTLEMENTS_A,
    ID.GLOOMHAVEN_BATTLEMENTS_B,
    ID.GHOST_FORTRESS,
    ID.THE_VOID,
    ID.NOXIOUS_CELLAR,
    ID.INVESTIGATION,
    ID.BLOODY_SHACK,
    ID.ALCHEMY_LAB,
    ID.VAULT_OF_SECRETS,
    ID.SACRIFICE_PIT,
    ID.SHADOWS_WITHIN,
    ID.HARRIED_VILLAGE,
    ID.PLANE_OF_WATER,
    ID.SYNDICATE_HIDEOUT,
    ID.BACK_ALLEY_BRAWL,
  ].filter(v => v !== id);
}
