export default {
  CHECKMARKS: 'Checkmarks',
  CHOOSE_1_SCENARIO: 'Choose1Scenario',
  CITY_EVENT: 'CityEvent',
  CLASS: 'Class',
  COLLECTIVE_GOLD: 'CollectiveGold',
  CONDITIONAL_GLOBAL_ACHIEVEMENT: 'ConditionalGlobalAchievement',
  EITHER: 'Either',
  ENVELOPE: 'Envelope',
  GLOBAL_ACHIEVEMENT: 'GlobalAchievement',
  GOLD: 'Gold',
  ITEM: 'Item',
  ITEM_2X: 'Item2x',
  ITEM_DESIGN: 'ItemDesign',
  LOST_PARTY_ACHIEVEMENT: 'LostPartyAchievement',
  PARTY_ACHIEVEMENT: 'PartyAchievement',
  PROSPERITY: 'Prosperity',
  SCENARIO: 'Scenario',
  REPUTATION: 'Reputation',
  RETIRE: 'Retire',
  XP: 'XP',
};
