import ID from './ID';

export default {
  [ID.ANCIENT_ARTILLERY]: { id: ID.ANCIENT_ARTILLERY, name: 'Ancient Artillery' },
  [ID.BANDIT_ARCHER]: { id: ID.BANDIT_ARCHER, name: 'Bandit Archer' },
  [ID.BANDIT_GUARD]: { id: ID.BANDIT_GUARD, name: 'Bandit Guard' },
  [ID.BLACK_IMP]: { id: ID.BLACK_IMP, name: 'Black Imp' },
  [ID.CAVE_BEAR]: { id: ID.CAVE_BEAR, name: 'Cave Bear' },
  [ID.CITY_ARCHER]: { id: ID.CITY_ARCHER, name: 'City Archer' },
  [ID.CITY_GUARD]: { id: ID.CITY_GUARD, name: 'City Guard' },
  [ID.CULTIST]: { id: ID.CULTIST, name: 'Cultist' },
  [ID.DEEP_TERROR]: { id: ID.DEEP_TERROR, name: 'Deep Terror' },
  [ID.EARTH_DEMON]: { id: ID.EARTH_DEMON, name: 'Earth Demon' },
  [ID.FLAME_DEMON]: { id: ID.FLAME_DEMON, name: 'Flame Demon' },
  [ID.FROST_DEMON]: { id: ID.FROST_DEMON, name: 'Frost Demon' },
  [ID.FOREST_IMP]: { id: ID.FOREST_IMP, name: 'Forest Imp' },
  [ID.GIANT_VIPER]: { id: ID.GIANT_VIPER, name: 'Giant Viper' },
  [ID.HARROWER_INFESTER]: { id: ID.HARROWER_INFESTER, name: 'Harrower Infester' },
  [ID.HOUND]: { id: ID.HOUND, name: 'Hound' },
  [ID.INOX_ARCHER]: { id: ID.INOX_ARCHER, name: 'Inox Archer' },
  [ID.INOX_GUARD]: { id: ID.INOX_GUARD, name: 'Inox Guard' },
  [ID.INOX_SHAMAN]: { id: ID.INOX_SHAMAN, name: 'Inox Shaman' },
  [ID.LIVING_BONES]: { id: ID.LIVING_BONES, name: 'Living Bones' },
  [ID.LIVING_CORPSE]: { id: ID.LIVING_CORPSE, name: 'Living Corpse' },
  [ID.LIVING_SPIRIT]: { id: ID.LIVING_SPIRIT, name: 'Living Spirit' },
  [ID.LURKER]: { id: ID.LURKER, name: 'Lurker' },
  [ID.OOZE]: { id: ID.OOZE, name: 'Ooze' },
  [ID.NIGHT_DEMON]: { id: ID.NIGHT_DEMON, name: 'Night Demon' },
  [ID.RENDING_DRAKE]: { id: ID.RENDING_DRAKE, name: 'Rending Drake' },
  [ID.SAVVAS_ICESTORM]: { id: ID.SAVVAS_ICESTORM, name: 'Savvas Icestorm' },
  [ID.SAVVAS_LAVAFLOW]: { id: ID.SAVVAS_LAVAFLOW, name: 'Savvas Lavaflow' },
  [ID.SPITTING_DRAKE]: { id: ID.SPITTING_DRAKE, name: 'Spitting Drake' },
  [ID.STONE_GOLEM]: { id: ID.STONE_GOLEM, name: 'Stone Golem' },
  [ID.SUN_DEMON]: { id: ID.SUN_DEMON, name: 'Sun Demon' },
  [ID.VERMLING_SCOUT]: { id: ID.VERMLING_SCOUT, name: 'Vermling Scout' },
  [ID.VERMLING_SHAMAN]: { id: ID.VERMLING_SHAMAN, name: 'Vermling Shaman' },
  [ID.WIND_DEMON]: { id: ID.WIND_DEMON, name: 'Wind Demon' },
  [ID.BANDIT_COMMANDER]: { id: ID.BANDIT_COMMANDER, name: 'Bandit Commander', boss: true },
  [ID.THE_BETRAYER]: { id: ID.THE_BETRAYER, name: 'The Betrayer', boss: true },
  [ID.CAPTAIN_OF_THE_GUARD]: { id: ID.CAPTAIN_OF_THE_GUARD, name: 'Captain of the Guard', boss: true },
  [ID.THE_COLORLESS]: { id: ID.THE_COLORLESS, name: 'The Colorless', boss: true },
  [ID.DARK_RIDER]: { id: ID.DARK_RIDER, name: 'Dark Rider', boss: true },
  [ID.ELDER_DRAKE]: { id: ID.ELDER_DRAKE, name: 'Elder Drake', boss: true },
  [ID.THE_GLOOM]: { id: ID.THE_GLOOM, name: 'The Gloom', boss: true },
  [ID.INOX_BODYGUARD]: { id: ID.INOX_BODYGUARD, name: 'Inox Bodyguard', boss: true },
  [ID.JEKSERAH]: { id: ID.JEKSERAH, name: 'Jekserah', boss: true },
  [ID.MERCILESS_OVERSEER]: { id: ID.MERCILESS_OVERSEER, name: 'Merciless Overseer', boss: true },
  [ID.PRIME_DEMON]: { id: ID.PRIME_DEMON, name: 'Prime Demon', boss: true },
  [ID.THE_SIGHTLESS_EYE]: { id: ID.THE_SIGHTLESS_EYE, name: 'The Sightless Eye', boss: true },
  [ID.WINGED_HORROR]: { id: ID.WINGED_HORROR, name: 'Winged Horror', boss: true },
};
