import ID from './ID';

export default {
  [ID.A_DEMONS_ERRAND]: { id: ID.A_DEMONS_ERRAND, name: "A Demon's Errand" },
  [ID.A_MAP_TO_TREASURE]: { id: ID.A_MAP_TO_TREASURE, name: 'A Map to Treasure' },
  [ID.ACROSS_THE_DIVIDE]: { id: ID.ACROSS_THE_DIVIDE, name: 'Across the Divide' },
  [ID.AN_INVITATION]: { id: ID.AN_INVITATION, name: 'An Invitation' },
  [ID.BAD_BUSINESS]: { id: ID.BAD_BUSINESS, name: 'Bad Business' },
  [ID.DARK_BOUNTY]: { id: ID.DARK_BOUNTY, name: 'Dark Bounty' },
  [ID.DEBT_COLLECTION]: { id: ID.DEBT_COLLECTION, name: 'Debt Collection' },
  [ID.FIRST_STEPS]: { id: ID.FIRST_STEPS, name: 'First Steps' },
  [ID.FISHS_AID]: { id: ID.FISHS_AID, name: "Fish's Aid" },
  [ID.FOLLOWING_CLUES]: { id: ID.FOLLOWING_CLUES, name: 'Following Clues' },
  [ID.GRAVE_JOB]: { id: ID.GRAVE_JOB, name: 'Grave Job' },
  [ID.HIGH_SEA_ESCORT]: { id: ID.HIGH_SEA_ESCORT, name: 'High Sea Escort' },
  [ID.JEKSERAHS_PLANS]: { id: ID.JEKSERAHS_PLANS, name: "Jekserah's Plans" },
  [ID.REDTHORNS_AID]: { id: ID.REDTHORNS_AID, name: "Redthorn's Aid" },
  [ID.SIN_RA]: { id: ID.SIN_RA, name: 'Sin-Ra' },
  [ID.STONEBREAKERS_CENSER]: { id: ID.STONEBREAKERS_CENSER, name: "Stonebreaker's Censer" },
  [ID.THE_DRAKES_COMMAND]: { id: ID.THE_DRAKES_COMMAND, name: "The Drake's Command" },
  [ID.THE_DRAKE_SLAIN_INVALID]: { id: ID.THE_DRAKE_SLAIN_INVALID, name: 'The Drake Slain' },
  [ID.THE_DRAKES_TREASURE]: { id: ID.THE_DRAKES_TREASURE, name: "The Drake's Treasure" },
  [ID.THE_POISONS_SOURCE]: { id: ID.THE_POISONS_SOURCE, name: "The Poison's Source" },
  [ID.THE_SCEPTER_AND_THE_VOICE]: { id: ID.THE_SCEPTER_AND_THE_VOICE, name: 'The Scepter and the Voice' },
  [ID.THE_VOICES_COMMAND]: { id: ID.THE_VOICES_COMMAND, name: "The Voice's Command" },
  [ID.THE_VOICES_TREASURE]: { id: ID.THE_VOICES_TREASURE, name: "The Voice's Treasure" },
  [ID.THROUGH_THE_NEST]: { id: ID.THROUGH_THE_NEST, name: 'Through the Nest' },
  [ID.THROUGH_THE_RUINS]: { id: ID.THROUGH_THE_RUINS, name: 'Through the Ruins' },
  [ID.THROUGH_THE_TRENCH]: { id: ID.THROUGH_THE_TRENCH, name: 'Through the Trench' },
  [ID.TREMORS]: { id: ID.TREMORS, name: 'Tremors' },
  [ID.WATER_STAFF]: { id: ID.WATER_STAFF, name: 'Water Staff' },
};
