import ID from './ID';

export default {
  [ID.NO_RECOVER]: { id: ID.NO_RECOVER, name: 'Cannot Recover Ability' },
  [ID.RECOVER]: { id: ID.RECOVER, name: 'Recover' },
  [ID.ATTACK]: { id: ID.ATTACK, name: 'Attack' },
  [ID.ATTACK_NEG1]: { id: ID.ATTACK_NEG1, name: '-1 Attack Modifier' },
  [ID.PERSISTENT]: { id: ID.PERSISTENT, name: 'Persistent Bonus' },
  [ID.ROUND]: { id: ID.ROUND, name: 'Round Bonus' },
  [ID.CHECKMARK]: { id: ID.CHECKMARK, name: 'Checkmark' },
  [ID.CONSUMED]: { id: ID.CONSUMED, name: 'Lost or Consumed' },
  [ID.EVENT_REMOVE_FROM_GAME]: { id: ID.EVENT_REMOVE_FROM_GAME, name: 'Remove from Game' },
  [ID.EVENT_RETURN_TO_DECK]: { id: ID.EVENT_RETURN_TO_DECK, name: 'Return to Deck' },
  [ID.FLYING]: { id: ID.FLYING, name: 'Flying' },
  [ID.HEAL]: { id: ID.HEAL, name: 'Heal' },
  [ID.ITEM_REFRESH]: { id: ID.ITEM_REFRESH, name: 'Refresh' },
  [ID.ITEM_SPENT]: { id: ID.ITEM_SPENT, name: 'Spend' },
  [ID.JUMP]: { id: ID.JUMP, name: 'Jump' },
  [ID.LOOT]: { id: ID.LOOT, name: 'Loot' },
  [ID.MOVE]: { id: ID.MOVE, name: 'Move' },
  [ID.PLUS1]: { id: ID.PLUS1, name: '+1' },
  [ID.RANGE]: { id: ID.RANGE, name: 'Range' },
  [ID.RETALIATE]: { id: ID.RETALIATE, name: 'Retaliate' },
  [ID.SHIELD]: { id: ID.SHIELD, name: 'Shield' },
  [ID.SHUFFLE]: { id: ID.SHUFFLE, name: 'Shuffle' },
  [ID.TARGET]: { id: ID.TARGET, name: 'Target' },
  [ID.USE_SLOT]: { id: ID.USE_SLOT, name: 'Use Slot' },
  [ID.USE_SLOT_GAIN_XP]: { id: ID.USE_SLOT_GAIN_XP, name: 'Use Slot Gain XP' },
  [ID.USE_SLOT_GAIN_XP_1]: { id: ID.USE_SLOT_GAIN_XP_1, name: 'Use Slot Gain 1 XP' },
  [ID.USE_SLOT_GAIN_XP_2]: { id: ID.USE_SLOT_GAIN_XP_2, name: 'Use Slot Gain 2 XP' },
  [ID.XP]: { id: ID.XP, name: 'XP' },
};
